### ISSUE TITLE
Calculating the fee when reconfiguring a target is annoying

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-interface#100]
I want to put in the exact amount I want to pay out, and have the fee calculated for me.

![image](https://user-images.githubusercontent.com/77952627/130326393-54351b4d-aa1c-4b83-999e-e1e70bfcea32.png)

**Comment by aeolianeth** [comment]
@johnnyd-eth assigning you as I think your work in https://github.com/jbx-protocol/juice-interface/pull/313 will resolve this issue 😄

**Comment by johnnyd-eth** [comment]
> @johnnyd-eth assigning you as I think your work in #313 will resolve this issue 😄

Indeed!
