### ISSUE TITLE
Antd error messages black on dark theme

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1000]
## Description

<img width="602" alt="Screen Shot 2022-05-12 at 6 52 25 pm" src="https://user-images.githubusercontent.com/96150256/168138170-5f0e72c9-2dbf-4e10-8497-10cb298b127e.png">

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by wraeth-eth** [comment]
I think this one goes away with my update to antd in https://github.com/jbx-protocol/juice-interface/pull/1003

**Comment by wraeth-eth** [comment]
fixed with above merge
