### ISSUE TITLE
Improve reconfigure UX

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1013]
## Description

There is confusion around reconfigurations. We need to make it very clear that users aren't configuring their current funding cycle - they are configuring their _next_ one.

Lets brainstorm ways of doing this.

**Comment by johnnyd-eth** [comment]
Is this still true in V2? I feel like it's clear AF, but if users are still telling us this we should definitely do something else

<img width="618" alt="Screen Shot 2022-06-05 at 6 36 47 pm" src="https://user-images.githubusercontent.com/96150256/172063109-261a5ac1-4897-499a-8290-10626138fe10.png">

<img width="645" alt="Screen Shot 2022-06-05 at 6 36 56 pm" src="https://user-images.githubusercontent.com/96150256/172063121-079bf131-3ec7-47d1-a817-365c26eba21a.png">

**Comment by aeolianeth** [comment]
THink it will be solved with https://github.com/jbx-protocol/juice-interface/issues/1106.

Closing
