### ISSUE TITLE
Improve pay process when wallet disconnected

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1014]
## Description

From UX standpoint would be nice to disable the pay button and show a tooltip asking user to connect wallet on project page rather than throwing a mysterious transaction reverted error when they attempt to pay.

## Proposal

in general it'd be nice if we had a component like WalletConnectedButton which is basically an antd button with a disabled guard for wallet connected = True, and a tooltip that asks user to connect wallet if it's not connected.

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by johnnyd-eth** [comment]
We talked about this a while ago, and Jango and Peri liked the idea of people being able to get to as many places around the site as possible without a wallet connected. I don't see a problem letting people get to the end of the pay flow without having a wallet connected - if they're new to web3 and don't have a wallet, it may help them better understand the 'money in, token back' mechanics

**Comment by johnnyd-eth** [comment]
However, can see a problem where the pay modal closes upon connecting. Will look at keeping the modal open and with the previously inputted amount still there after connecting
