### ISSUE TITLE
Twitter Verification

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1022]
## Problem to solve

Implement Twitter OAuth verification to help filter out imposter projects.

## Proposal

Add 'Connect Twitter' button beneath the Twitter account input field in Project reconfigure, and use that to allow OAuth connection to Twitter. Display Twitter-style checkmark next to Twitter account handle.

## More details

Will require a new metadata version for checking whether a project is verified, so may be worth bundling this PR with any other metadata changes we're thinking about.

**Comment by peripheralist** [comment]
keep in mind any project can upload a json file to IPFS to use as their project metadata, so i'm not sure we could store verification there. we'd need to have some other auth-protected storage
