### ISSUE TITLE
Style bug in drawer styles

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1064]
## Summary

<img width="623" alt="image" src="https://user-images.githubusercontent.com/33093632/170042987-0b4ad9a9-894c-4252-a171-800d71207803.png">

## Steps to reproduce

Open any drawer

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by aeolianeth** [comment]
@jmilldotdev cool if you take this one for FC22? Will assign you for now at least <3
