### ISSUE TITLE
Bump antd version to 4.20

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1067]
## Description

Antd 4.20 adds some very useful new features including a watcher hook for form values. Plus how could we not?

## Proposal

https://ant.design/components/form/#API

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by aeolianeth** [comment]
Assigning this to @wraeth-eth who as an open pR

https://github.com/jbx-protocol/juice-interface/pull/1012

**Comment by aeolianeth** [comment]
@wraeth-eth ive added this to FC22 but lemme know if thats too much <3

**Comment by jmilldotdev** [comment]
@wraeth-eth you still plan to tackle this soon? form.useWatch would be really helpful for the veBanny staking form.

**Comment by aeolianeth** [comment]
@jmilldotdev on it
