### ISSUE TITLE
[Parent] veNFT MVP

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1154]
## Dev

- [x] https://github.com/jbx-protocol/juice-interface/issues/1411
- [x] https://github.com/jbx-protocol/juice-interface/issues/1412
- [x] https://github.com/jbx-protocol/juice-interface/issues/1413
- [x] https://github.com/jbx-protocol/juice-interface/issues/1414
- [x] https://github.com/jbx-protocol/juice-interface/issues/1415

## UX

- [x] https://github.com/jbx-protocol/juice-interface/issues/1521
- [x] https://github.com/jbx-protocol/juice-interface/issues/1522
- [x] https://github.com/jbx-protocol/juice-interface/issues/1524

**Comment by jmilldotdev** [comment]
Gonna close this. We're live on rinkeby.
