### ISSUE TITLE
Launch funding cycle modal UX improvements

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1175]
## Description

From a UX perspective it feels kind of painful to ask a user to input a generally large, precise number in seconds. Feels like user should be able to input their value in days/hours by default, with the option to get down to seconds if they really need to.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/33093632/172613365-d6927795-8f4d-45fe-af1b-f0be652d1e94.png">

**Comment by 0xbakedpotato** [comment]
https://ant.design/components/date-picker/#header, ant design has a bunch of date/time fields that we could implement rather than force users to come up with the Unix time stamp.

Happy to grab this issue.

**Comment by aeolianeth** [comment]
Closing this for now as I dont think we need to optimize this modal (it's only temporarily in the codebase)
