### ISSUE TITLE
Add owner on project's header

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1187]
## Problem to solve

<img width="652" alt="Screen Shot 2022-06-09 at 11 31 29 pm" src="https://user-images.githubusercontent.com/96150256/172948963-0836d3d3-8e94-472b-ab2d-c5d99e37c2b0.png">

## Proposal

_Describe the feature/solution you'd like. A clear and concise description of
what you want to happen._

## More details

_Add any other notes or screenshots about the feature request here._

**Comment by 0xbakedpotato** [comment]
Hi there,

Happy to grab this task if no one is working on it yet.
