### ISSUE TITLE
Percent slider on payouts lags when clicked 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1196]
## Summary

When clicking percent slider, percent changes but slider does not. Always one position behind the actual percent. Also had some user complaints about this ('% slider was sketchy so I used the input')

https://user-images.githubusercontent.com/96150256/173154528-9d510c31-c36e-479a-9e3c-c374607e1a7a.mp4

## Steps to reproduce

1. Click percent slider
2. See percent change
3. See slider does not change

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by wraeth-eth** [comment]
@johnnyd-eth I actually have a little experience with fixing this - often comes down to some refactoring of the antd stuff to let antd handle more of the dynamic stuff. Happy to take it off your hands, unless you really wanna do it 😛

**Comment by johnnyd-eth** [comment]
> @johnnyd-eth I actually have a little experience with fixing this - often comes down to some refactoring of the antd stuff to let antd handle more of the dynamic stuff. Happy to take it off your hands, unless you really wanna do it 😛

Nice ser you go for it!

**Comment by wraeth-eth** [comment]
Hey @johnnyd-eth can you confirm if you still have this on main? It might have been fixed. I did something to a form somewhere on a PR, but don't remember what 😅 , maybe already fixed

https://user-images.githubusercontent.com/104132113/174934017-9c767bf8-f0a8-468c-abb0-f970a8e8d7df.mov

**Comment by johnnyd-eth** [comment]
Weird @wraeth-eth that does seemed to be fixed now lol. Too easy
