### ISSUE TITLE
v2: mint token failure causes transaction pending

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#1215]
## Summary

Causes a popup that is unrecoverable (without refreshing).

## Relevant logs and/or screenshots

https://user-images.githubusercontent.com/104132113/173223494-0b1367e0-f106-44e3-8d92-4bd47614e242.mov

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by 0xbakedpotato** [comment]
Happy to grab this if no one is working on it!
