### ISSUE TITLE
Add percentage slider for redeem and claim tokens.

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1219]
<img width="782" alt="Screen Shot 2022-06-13 at 9 58 46 AM" src="https://user-images.githubusercontent.com/94939382/173260108-16f0fa98-2156-432d-b440-68385d30af07.png">

**Comment by tomquirk** [comment]
Closing, duplcate of https://github.com/jbx-protocol/juice-interface/issues/500
