### ISSUE TITLE
Show images as a delete-able preview in the pay memo input field

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1223]

**Comment by 0xbakedpotato** [comment]
I'm happy to grab this one. @johnnyd-eth, is there any more context here that I'd need?

**Comment by johnnyd-eth** [comment]
> I'm happy to grab this one. @johnnyd-eth, is there any more context here that I'd need?

Sweet @0xbakedpotato! And I don't think so - we just want images that are attached from the 'Add image' or the new sticker modal to show up as images instead of their URL's mainly. But also would be great to remove with them with an X button

**Comment by aeolianeth** [comment]
@benschac I'm going to give this one to @wraeth-eth because he's working on related work.

**Comment by benschac** [comment]
I'm pretty close to finishing it up. I'd likely have a PR up tomorrow. Also, not married to the task in @wraeth-eth wants to grab it.
