### ISSUE TITLE
Make payment feed items render multiple memo images and format them nicely

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1224]
When you attach multiple images (or stickers) to payment memos, they look like this (only renders last image):

<img width="549" alt="Screen Shot 2022-06-28 at 10 26 10 pm" src="https://user-images.githubusercontent.com/96150256/176178217-f98ace27-fc7b-4140-8ee5-c5d5271c84fa.png">

We should have them all rendering and lining up on one row (side-by-side)

**Comment by aeolianeth** [comment]
@johnnyd-eth could you please add more detail here? :)
