### ISSUE TITLE
Project creation: Add fee explainer to the Funding drawer

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1244]
Need to add a note about the 2.5% fee for non-Juicebox projects to the main drawer.

User feedback:

https://discord.com/channels/775859454780244028/775859454780244031/986623033173213204

![Image](https://user-images.githubusercontent.com/94939382/173842763-c7af8d10-af5f-40c7-a43f-a9b96d705958.png)

**Comment by wraeth-eth** [comment]
Hey @aeolianeth - I might need a bit of info on this one 😅 what does it mean by non-juicebox projects?

**Comment by aeolianeth** [comment]
@wraeth-eth payouts to juicebox project dont incur the fee, whereas payouts to wallet addresses incur a 2.5% fee.

This issue is to explain that somewhere in the Funding form in project creation.
