### ISSUE TITLE
Improve Funding form UX

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1246]
Many projects will want to simply set a funding target.

How might we make that clearer in UI?

User feedback:

- https://discord.com/channels/775859454780244028/775859454780244031/986623033173213204
- Note also incoming user feedback from @Majordalaw 

![Image](https://user-images.githubusercontent.com/94939382/173846545-f2132e99-d1dc-4497-a0d7-9d161a0f0609.png)

**Comment by johnnyd-eth** [comment]
Working on this. Will drop a prog update soon
