### ISSUE TITLE
Activity Feed Images Aspect Ratio broken on Safari

### ISSUE THREAD

**Issue by 0xbakedpotato** [jbx-protocol/juice-interface#1266]
## Summary

Activity Feed images are stretched out of aspect ratio on Safari Browser.
### Safari
<img width="1113" alt="CleanShot 2022-06-21 at 12 11 56@2x" src="https://user-images.githubusercontent.com/107800399/174847661-d527520d-258a-4800-bbef-1c1550dcd362.png">

### Chrome
<img width="1580" alt="CleanShot 2022-06-21 at 12 21 05@2x" src="https://user-images.githubusercontent.com/107800399/174849132-b761e852-67e6-487f-bf59-170ed44d2cc4.png">

## Steps to reproduce

1. Go to `https://juicebox.money/#/v2/p/31`
2. Scroll to images on activity feed

## What is the _current_ bug behavior?
Images are stretched past their aspect ratio.

## What is the expected _correct_ behavior?
Safari Activity Images should look like Activity Images in Chrome.
## Relevant logs and/or screenshots
Above

## Environment

- **Device/OS**: [e.g. MacOS]
- **Browser:** [safari]

**Comment by benschac** [comment]
Looked into it a bit more, and I think the fix might be a little more involved than just a quick CSS fix. I'll take a look next week. This will be the top of my list.
