### ISSUE TITLE
Wrong Wallet Connecting on Gnosis Safe

### ISSUE THREAD

**Issue by filipvvv** [jbx-protocol/juice-interface#1299]
## Summary

When Metamask is connected to Juicebox.money, that Metamask address will automatically connect to the Gnosis Safe app in another tab (instead of the Gnosis Safe wallet).

## Steps to reproduce

1. Go to juicebox.money and connect Metamask.
2. Open a Gnosis Safe in another tab.
3. Add the juicebox.money app to your Gnosis Safe.
4. See error.

## What is the _current_ bug behavior?

Inconsistent behavior when loading the juicebox.money app in Gnosis Safe. For some users, a Metamask wallet from another tab will connect instead of the Safe wallet.

## What is the expected _correct_ behavior?

Gnosis Safe wallet connects automatically.

## Relevant logs and/or screenshots

[Demonstration](https://www.loom.com/share/a65875f1928149ad96af700c9754f850) from [Mikhailxyz](https://github.com/mikhailxyz)

Also see [my attempts to recreate](https://www.notion.so/juicebox/Demonstrations-f6ea2f8cbaf34d43a73dcf0751a56bb0). In one attempt, had different unexpected behavior. In my second attempt, had expected behaviour.

## Environment

- **Device/OS**: Not sure of Mikhail's, can check. Mine on Arch 5.18.7.
- **Browser:** Chrome, Firefox, Developer Firefox
- **Hardware wallet**: None (metamask)

**Comment by wraeth-eth** [comment]
Hey @filipvvv , I just ran through your steps and I didn't see an error. Could you try again and see if it is still occurring?

**Comment by filipvvv** [comment]
@wraeth-eth tried this a few times and it's working well for me. Unless you have any further tests, we can close this one.

**Comment by wraeth-eth** [comment]
> @wraeth-eth tried this a few times and it's working well for me. Unless you have any further tests, we can close this one.

Thanks @filipvvv , will close for now and we can re-open in the future if it rears its head again
