### ISSUE TITLE
Inconsistent Wallet Connect Experience on Firefox

### ISSUE THREAD

**Issue by filipvvv** [jbx-protocol/juice-interface#1300]
## Summary

Connect button does not bring up Metamask sign-in modal... usually.

## Steps to reproduce

1. Go to juicebox.money
2. Click on connect
3. See error

## Relevant logs and/or screenshots

See [Metamask prompt fail](https://www.notion.so/juicebox/Demonstrations-f6ea2f8cbaf34d43a73dcf0751a56bb0). Also note that network switch is not prompted when switching from Rinkeby to mainnet. Sometimes have the opposite issue (no prompt when going from mainnet to Rinkeby).

## Environment

- **Device/OS**: Thinkpad x220, 5.18.7-arch1-1.
- **Browser:** Firefox
- **Hardware wallet**: N/A

**Comment by wraeth-eth** [comment]
I think this might be fixed with wallet changes made in July/August. DO you think you could retry this one too, @filipvvv ? 🙏

**Comment by filipvvv** [comment]
@wraeth-eth working now!

**Comment by filipvvv** [comment]
@wraeth-eth never mind. Was able to reproduce issue:

1. Reboot computer, open Firefox.
2. Connect MetaMask to juicebox.money (works as intended)
3. Close and re-open Firefox.
4. Try connecting to juicebox.money again (not prompted).

To fix, manually log in to MetaMask, and then refresh and press connect until it works (sometimes takes two or three attempts).

Will get a screen recording up shortly.

**Comment by filipvvv** [comment]
https://user-images.githubusercontent.com/96905094/215046667-e89812c3-7f10-4cf5-85a1-598f9a1445a1.mp4

**Comment by wraeth-eth** [comment]
> firefox-issue.mp4

@filipvvv ah awesome! Thank you for this, should help in hopefully finding a fix 🙏

**Comment by wraeth-eth** [comment]
Ah yep - this is because metamask is locked. For some reason (on firefox) it prompts me immediately to login

https://user-images.githubusercontent.com/104132113/215613070-81145989-8a1b-4222-b24e-4657ce193c8c.mov

**Comment by wraeth-eth** [comment]
I can recreate the same behavior by doing this:

From a successfully unlocked and connected state to JB:
1. Disconnect from JB
2. Lock MM wallet
3. Click Connect -> MM but don't sign into MM
4. Close MM and JB Connect Prompt
5. Attempt to Connect again and see it says connecting

**Comment by wraeth-eth** [comment]
Actually the behavior is still different - my wallet does eventually connect correctly without a refresh. Let me keep digging

**Comment by wraeth-eth** [comment]
> @wraeth-eth never mind. Was able to reproduce issue:
> 
> 1. Reboot computer, open Firefox.
> 2. Connect MetaMask to juicebox.money (works as intended)
> 3. Close and re-open Firefox.
> 4. Try connecting to juicebox.money again (not prompted).
> 
> To fix, manually log in to MetaMask, and then refresh and press connect until it works (sometimes takes two or three attempts).
> 
> Will get a screen recording up shortly.

Just tried these steps verbatim and still get the same behavior as above. I wonder if there is some difference in behavior between linux and macos. 

For my sessions, on page load, metamask is automatically prompted when not connected on first page load 🤔

**Comment by wraeth-eth** [comment]
Can someone else from @jbx-protocol/frontend try @filipvvv steps on a mac so we can try and narrow down the problem

**Comment by wraeth-eth** [comment]
++ if you have a linux machine to test on too

**Comment by filipvvv** [comment]
> Just tried these steps verbatim and still get the same behavior as above. I wonder if there is some difference in behavior between linux and macos.

Very likely. I'm also using a relatively uncommon system — Arch Linux on an old Thinkpad. If you aren't having this issue on more common systems, this probably isn't worth prioritizing.

**Comment by wraeth-eth** [comment]
> > Just tried these steps verbatim and still get the same behavior as above. I wonder if there is some difference in behavior between linux and macos.
> 
> Very likely. I'm also using a relatively uncommon system — Arch Linux on an old Thinkpad. If you aren't having this issue on more common systems, this probably isn't worth prioritizing.

Ah gotcha, thanks @filipvvv ! I am going to close this one, but if you happen to run into this again or it gets worse, feel free to re-open
