### ISSUE TITLE
V1 project owner address isn't rendering

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1306]
## Summary

_A clear and concise description of what the bug is._

## Steps to reproduce

1. Go to a V1 project page, juicebox.money/#/p/juicebox
3. Scroll down to **payouts**
4. Observe. The owner address isn't rendering.

## What is the _current_ bug behavior?

Project owner address not rendering.

## What is the expected _correct_ behavior?

Project owner address should render.

## Relevant logs and/or screenshots

<img width="501" alt="Screen Shot 2022-07-01 at 8 14 06 AM" src="https://user-images.githubusercontent.com/94939382/176790813-7ed50d21-c297-400a-a860-9fe3b5031c7f.png">

**Comment by benschac** [comment]
I can grab this. I just worked on something similar
