### ISSUE TITLE
Simplify `Token` form

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1327]
## Description

The **Token** form/drawer needs to be simpler.

## Screenshots

<img width="1327" alt="Screen Shot 2022-07-19 at 9 56 29 AM" src="https://user-images.githubusercontent.com/12551741/179638696-49ae27bd-a2d6-4cdc-b036-df8c829c8813.png">

**Comment by strath-m** [comment]
Link to thread: https://discord.com/channels/939317843059679252/970421807767236708/999120040840413234
