### ISSUE TITLE
Refactor index.ts files to contain re-export logic only

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1331]
## Description

Our index.ts files contain application code. This makes code discoverability harder, because the file name doesn't match the contents of the component.

## Proposal

`index.ts` should be just for re-routing exports.

This issue is to refactor index.ts files so that they only export components. Existing code in `index.ts` files should move to a file that's more appropriately named.

This could be done across multiple PRs.

Example from @wraeth-eth 

```js
// test/Test.tsx
export const Test = () => {
  return <></>
}

// index.ts
import {Test} from './Test'

export default Test
```

**Comment by tomquirk** [comment]
I think we can do this overtime without the need for a specific issue. Closing.
