### ISSUE TITLE
Error in hook structure in EditPayoutsModal

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#1344]
## Summary

Structure of hooks throws an error, unclear if it's affecting performance.
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/79433522/177355872-47c934c5-ef58-4670-9869-ffebfddf01c9.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/79433522/177355933-1712d846-6b20-4e48-a2ee-589916adae1b.png">

## Steps to reproduce

1. Load project page
2. Check browser console

## Environment

- **Device/OS**: Macbook
- **Browser:** Brave

**Comment by wraeth-eth** [comment]
Hey @peripheralist can you confirm this is still happening? I am having trouble recreating. I have tried both:
http://localhost:3000/#/v2/p/44
http://localhost:3000/#/p/juicebox

**Comment by wraeth-eth** [comment]
I haven't been able to recreate this and am currently busy with the nextjs stuf at the moment. If anyone has capacity or is looking for something to do, feel free to pick this one up
