### ISSUE TITLE
Restrict using the same address multiple times for reserve tokens

### ISSUE THREAD

**Issue by odd-amphora** [jbx-protocol/juice-interface#136]
I feel like in the frontend we should probably try to prevent this from happening?
<img width="591" alt="Screen Shot 2021-09-13 at 3 03 48 PM" src="https://user-images.githubusercontent.com/88144767/133141788-e46c5975-a5e3-4724-a469-dfa68030aa9e.png">

**Comment by peripheralist** [comment]
yeah, in this case i think zeugh is the project owner, and is receiving the leftover 1% by default.

we can't restrict setting allocations to the project owner so this is a little tricky, but i think the UI also still allows duplicate allocations that should maybe be disallowed anyway.

**Comment by aeolianeth** [comment]
> but i think the UI also still allows duplicate allocations that should maybe be disallowed anyway.

@johnnyd-eth 👋 did you end up resolving this issue with https://github.com/jbx-protocol/juice-interface/pull/293?
