### ISSUE TITLE
Make `Distribute` activity element consistent with `Pay` event design

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1361]
## Description

Move **Distributed** amount to the top-left of the element.

This is to make it consistent with the `Pay` event design (and others).

| current | proposed |
| --- | --- |
| <img width="532" alt="Screen Shot 2022-07-08 at 12 54 49 PM" src="https://user-images.githubusercontent.com/94939382/177911007-5f281d0b-053d-459b-80f6-533fb95cfa78.png"> | <img width="530" alt="Screen Shot 2022-07-08 at 12 59 11 PM" src="https://user-images.githubusercontent.com/94939382/177911357-0e467d48-137a-4912-b2f2-4ead6a466853.png"> | 

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by midnight-madman** [comment]
This is closed by https://github.com/jbx-protocol/juice-interface/pull/1532
@aeolianeth
