### ISSUE TITLE
Make wallet connect never reload the page

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1370]
## Description

Sometimes when connecting wallet, the whole page reloads, causing any modals that were open to close. In some cases this is quite annoying to users who have to redo a form or something. 

Would be great if we could consistently have the whole page not reload when connecting the wallet. 

e.g. when paying with wallet disconnected, we should be able to have the final modal cta say 'Connect wallet to pay', have this open the wallet connect modal, then when the wallet is connected, the page DOES NOT reload, the pay modal stays open and the user can execute the pay tx straight away 

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by jmilldotdev** [comment]
I think this can be closed? @wraeth-eth @johnnyd-eth 

I don't see this happening anymore since the new onboarding
