### ISSUE TITLE
Remove owner % reserved rate when reserved rate is 0

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1373]
## Summary

<img width="555" alt="Screen Shot 2022-07-10 at 9 17 45 am" src="https://user-images.githubusercontent.com/96150256/178125788-ffadbe9d-f9a9-44c2-ba52-74481d529687.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by midnight-madman** [comment]
This is closed by https://github.com/jbx-protocol/juice-interface/pull/1646
@johnnyd-eth
