### ISSUE TITLE
Image upload broken for V1 payment memos

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#1384]
## Summary

Images aren't getting attached to payment memos in V1.

## Steps to reproduce

1. Go to a V1 project
2. Enter any amount in the **Pay** amount.
3. Click **Pay** button to open modal
4. Upload image
5. Open dev tools and find the `Calling pay() with args` log.
6. Observe `_memo` field. There is no image URL.

## What is the _current_ bug behavior?

Uploaded image URLs aren't appended to payment memos

## What is the expected _correct_ behavior?

Image URLs should be appended to payment memos

## Relevant logs and/or screenshots

<img width="1440" alt="Screen Shot 2022-07-12 at 6 42 38 AM" src="https://user-images.githubusercontent.com/94939382/178359510-b98a539a-c149-40db-835c-8343cd25a2f8.png">

**Comment by aeolianeth** [comment]
@wraeth-eth not sure if this was pre-existing bug, but would you mind taking a look? 🙏

**Comment by wraeth-eth** [comment]
@aeolianeth - no problem, bringing into current FC

**Comment by wraeth-eth** [comment]
Hey @aeolianeth - just quickly had a look into this, but I am not seeing the same problem. I followed your instructions but my memo looks like this:
```
{
    "_projectId": 44,
    "_amount": {
        "type": "BigNumber",
        "hex": "0x09184e72a000"
    },
    "_token": "0x000000000000000000000000000000000000eeee",
    "_beneficiary": "0x337699c1bca440d45be89c1c5af26348f0184cdf",
    "_minReturnedTokens": 0,
    "_preferClaimedTokens": false,
    "_memo": "\nhttps://jbx.mypinata.cloud/ipfs/QmSy76sgrP84smrxBXoRuvhVT8WVZfGNqJF3bwmrZG8KB7",
    "_metadata": 0
}
```

**Comment by wraeth-eth** [comment]
ignore above - I think i am on a v2 project, one sec
