### ISSUE TITLE
[BUG] Set Text record for "xxxxx.eth" errors with a rejected transaction

### ISSUE THREAD

**Issue by imadbz** [jbx-protocol/juice-interface#1387]
## Summary

_A clear and concise description of what the bug is._
While trying to set the handle, 1st transaction was fine, second one (setText) is throwing the following error
![image](https://user-images.githubusercontent.com/3145272/178385815-e0fd0a43-f959-4426-b9ea-89465897d6d5.png)

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by peripheralist** [comment]
hey @imadbz , can you verify the wallet you had connected is the owner/controller of xxxxx.eth? this error will happen if the wallet doesn't have permission to set the text record

**Comment by tomquirk** [comment]
Closing this for now @imadbz please re-open if you continue to have issues! 🙏
