### ISSUE TITLE
Improve project settings

### ISSUE THREAD

**Issue by tankbottoms** [jbx-protocol/juice-interface#1390]
## Description

Restructuring the project 'cog' to be a right-hand drawer with tabs, the first converting the modal to panels to make way for tabs for other project level reconfigurations - more complex token activities, permissions, NFT stuff.

## Proposal

Here is a prototype layout via Figma - https://www.figma.com/file/ffk6DLhm4sfOdZfU8xc27u/JB-Treasury-UX-Review?node-id=464%3A80118 - Treasury Settings Page

## Screenshots

![Screen Shot 2022-07-12 at 5 20 44 PM](https://user-images.githubusercontent.com/97219477/178598423-715c7efd-eb28-4d9f-97c5-f96883be9306.png)

## Prototype
You may need to click on a project you own to see the cog. 

https://bleeding-edge.juicebox.wtf/

**Comment by tomquirk** [comment]
Thanks for creating this issue @tankbottoms .

This is def a step in the right direction, however I think we should consider a few other options here.

For example, a dedicated Settings page for projects might be viable.

I think this is a good opportunity to do some "proper" user testing too.

**Comment by jmilldotdev** [comment]
Closed via https://github.com/jbx-protocol/juice-interface/pull/1875 MVP
