### ISSUE TITLE
Small pixel in perfection on dark mode banny main image

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#1401]
## Summary

There is a small pixel that needs cleaning up:

![image](https://user-images.githubusercontent.com/104132113/178848999-edd34d43-2821-4429-a9ee-a4e7ec8a23b0.png)

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by aeolianeth** [comment]
wtf lol 😂
