### ISSUE TITLE
Investigate new wallet connection libraries

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#1419]
## Description

We use https://www.npmjs.com/package/bnc-onboard however, it feels like it is causing problems (most notably https://github.com/jbx-protocol/juice-interface/issues/1410).

Two potential options (but not limited to) are:
1. https://www.rainbowkit.com/
2. https://docs.blocknative.com/onboard

**Comment by tomquirk** [comment]
Noting these related issues:

- https://github.com/jbx-protocol/juice-interface/issues/1300
- https://github.com/jbx-protocol/juice-interface/issues/1299

**Comment by jmilldotdev** [comment]
@wraeth-eth close this?
