### ISSUE TITLE
Stickers may not be rendering in activity feed

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1449]
## Summary

Zhape's payment included a sticker URL, but it didn't render the image.

https://www.juicebox.money/v2/p/66

<img width="1226" alt="Screen Shot 2022-07-20 at 4 56 44 PM" src="https://user-images.githubusercontent.com/12551741/179922488-f404569a-1b77-4c0b-a2d7-9348a9d6caa6.png">

**Comment by wraeth-eth** [comment]
No code change necessary - looks to be working:

![Image](https://user-images.githubusercontent.com/104132113/181933326-5c43de12-3801-4659-9298-53a4988cf103.png)
