### ISSUE TITLE
Project pages should have project-specific OpenGraph metadata

### ISSUE THREAD

**Issue by nnnnicholas** [jbx-protocol/juice-interface#145]
When shared in Discord and Twitter, project pages currently show Open Graph data for Juicebox: An image of Banny, the title "Juicebox", and a description of the protocol. This makes all project page shares look the same. 

## Issues

- [x] https://github.com/jbx-protocol/juice-interface/issues/1144

**Proposed solution**
Populate Open Graph metadata for project pages with project-specific metadata (title, image, description).

**Screenshots**
BrainDAO ograph data:
![image](https://user-images.githubusercontent.com/1418561/133950724-a1002fc2-b813-4363-9e64-2e926135d362.png)
![image](https://user-images.githubusercontent.com/1418561/133950847-3a261951-ffe4-4aba-81ae-8bd042d87186.png)

**Comment by peripheralist** [comment]
the main thing preventing us from doing this is the app's "hash routing", which apps hosted on IPFS need to use to be compatible with IPFS gateway route resolving. you'll notice that JB (and a lot of other IPFS apps, e.g. Uniswap) use a # in the url route. it makes it impossible to dynamically load <html/> holding the opengraph info for a specific page—we can only do it for the top level domain.

that said, there is probably a clever workaround we could come up with to make it still work, and i'd love to find it. anyone can feel free to tackle this.
 
![image](https://user-images.githubusercontent.com/79433522/134229023-fd6f3de5-6ca4-4f6e-84d0-17aca1635b21.png)

**Comment by peripheralist** [comment]
assigning this to you @palevoo since you're working on this, but i know it's still blocked for now so feel free to unassign if you get to an impass and wanna focus elsewhere

**Comment by jnoh** [comment]
One possible partial solution to this is to migrate from create-react-app to next.js so that we can get the [static generation](https://nextjs.org/docs/basic-features/pages#static-generation-recommended) magic that it provides (maybe we could figure out how to do this with create-react-app as well).

We can statically generate the top N projects so that there meta tags are properly filled in at build time. For any project that doesn't fall within N we would use generic text as we are doing now.

We'd want to keep it in N so that build times don't get out of hand as projects grow.

Not a full solution but an idea.

---

One total solution is to stop using IPFS/Fleek and have a proper backend so that we can SSR.

**Comment by peripheralist** [comment]
i'm open to using next if it would solve this. though it seems like the problem originates with how the app is hosted on ipfs—single page app with hash routing strategy—and not with react. i feel like if it could be solved using next, there must be a solution we could use with reactjs.

using a proper backend would certainly solve this. though hosting on ipfs keeps things transparent and doesn't require end users to be interacting with any centralized hosting service. for apps where users are connecting their wallets this seems pretty important. personally i'd be hesitant to send txs through any web3 app not hosted on a decentralized network

**Comment by jnoh** [comment]
Thinking here: https://www.notion.so/juicebox/Project-Specific-Link-Unfurling-a1ef79379bdb421abd20250667b0d8e9

**Comment by wraeth-eth** [comment]
This is now possible in a simple way with NextJS. We are almost there! However, we need to start doing some pre page rendering and caching I believe to carry us there. @aeolianeth I am pretty familiar with this from recent nextjs work, so if you're happy, i'd love to retain this ticket? ❤
