### ISSUE TITLE
Improve NFT Rewards display on Pay button

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1469]
Discussion:
- https://discord.com/channels/775859454780244028/990055537615970384/995834602809724948
- https://discord.com/channels/775859454780244028/990055537615970384/999558419679813742

**Comment by strath-m** [comment]
Have started designing and doing basic usability testing on an improved version of the NFT rewards. Will report back with findings and designs tomorrow.

**Comment by tomquirk** [comment]
@strath-m awesome ser keen to see it.
