### ISSUE TITLE
Handle transactions completed through Gnosis safe 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1470]
## Summary

**This error is related to the same problems as discussed on https://github.com/jbx-protocol/juice-interface/issues/2256**

<img width="783" alt="Screen Shot 2022-07-21 at 3 47 16 pm" src="https://user-images.githubusercontent.com/96150256/180147691-84cb95ad-5d9b-4060-832d-0af9154759da.png">

When executing on Gnosis safe, the dApp doesn't pick up that the transaction has gone through and remains in the pending state in the UI

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by wraeth-eth** [comment]
This is related to this https://github.com/jbx-protocol/juice-interface/issues/2256 and is a son-of-a-bitch to fix.
