### ISSUE TITLE
Add a like/heart button to payments

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#1472]
## Description

I think its no hidden fact that like/heart buttons are a great driver of user interaction and I think would be a pretty seamless addition.

My thoughts is that when you connect your wallet, you see an outlined ❤️  and can click it to add to a count. Any user can click to see a list of all wallets that have interacted with this post.

## Quick Mockup

<img width="612" alt="image" src="https://user-images.githubusercontent.com/104132113/180165659-e24c8806-acd1-4f94-b240-e3209113a210.png">

**Comment by wraeth-eth** [comment]
wdyt @strath-m ?

**Comment by strath-m** [comment]
Love it @wraeth-eth — as you said it incentivises further interaction with the platform and creates a familiar feel / mental model of similar social environments in the digital world. It will also drive motivation for contributors to add interesting/funny comments and images with their payments. If it's fairly easy to implement from your end I think it's a great idea.

**Comment by tomquirk** [comment]
Love. This idea has been floated many times. I think @peripheralist has done some previous thinking about implementation.

Would likes be on-chain? 🤔 

Idea (which i think is originally Jango's): do it via payment memos

- Have a special "like" payment memo that includes a transaction ID. `:thumbsup:_txid-0xabc`
- When someone clicks "like", they have to pay.
- UI renders "like" count based on payments that have the "like" payment memo

**Comment by wraeth-eth** [comment]
I’m not sure we want people to pay to like, would likely cause friction to usage

**Comment by strath-m** [comment]
Yeah I agree with @wraeth-eth about the friction part. Could add more emphasis to the 'like' but I think overall objective would be better to reduce friction. I'm sure there's a way to do it connected to your wallet address without paying gas or anything (similar to Opensea etc favourite/like function).

**Comment by tomquirk** [comment]
OpenSea have a database ;)

We could do that...but less cool.

Any initial thoughts on implementation @wraeth-eth ?

**Comment by wraeth-eth** [comment]
Yeah totally - I reckon db with the connected wallet address. Could cache the users ETH address on lookup too but not a necessity

**Comment by tomquirk** [comment]
full send

**Comment by peripheralist** [comment]
we'd prolly need a db for this. don't think we could use the IPFS cache pattern, since it isn't gonna be reliable with two different updates happening at the same time (i.e. multiple wallets hearting simultaneously)

**Comment by nnnnicholas** [comment]
idk how i feel about likes here tbh. i think i'd prioritize making them shareable first, ie "look vitalik donated to moondao LINK". just my 2 cents.
