### ISSUE TITLE
Fall back to a public IPFS gateway for Pinata requests

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1486]
## Description

If GET requests to Pinata fail (like GET project metadata), we don't do anything. The data in question may exist on IPFS, but it might not be available via our gateway (for whatever reason).

## Proposal

If GET requests fail, perform another GET request to a different, public IPFS gateway.

TBD which is the best gateway.

**Comment by jmilldotdev** [comment]
Partially covered by https://github.com/jbx-protocol/juice-interface/pull/1556

we just need to add this pattern to other IPFS get requests in the codebase
