### ISSUE TITLE
Change the Juicebox service key to reverse dot notation 

### ISSUE THREAD

**Issue by tankbottoms** [jbx-protocol/juice-interface#1495]
## Description

Change the project handle key from _juicebox_project_id to money.juicebox. 

## Proposal

Currently the project handles for Juicebox is in its own format, juicebox_project_id which is non-intuitive. It would be intuitive, follow convention to be in _reverse dot notation_ see [ENS.Domains documentation on Service keys](https://docs.ens.domains/ens-improvement-proposals/ensip-5-text-records#service-keys) thus money.juicebox would follow such convention. The limitation of having a one subdomain or ens address per project is also reasonable. 

The project 104 has one such record money.juicebox for your testing pleasure. 

## Screenshots

![Screen Shot 2022-07-22 at 3 59 51 PM](https://user-images.githubusercontent.com/97219477/180518472-45d09653-619c-4107-afdf-9e1651bf8893.png)

**Comment by tomquirk** [comment]
@peripheralist do you have thoughts here?

**Comment by peripheralist** [comment]
I don't think this is completely intuitive either. This standard would make sense if the text record were defining the handle (like money.juicebox=myhandle), but this record needs to specifically be the project's id
