### ISSUE TITLE
Improve veNFT stake form UX

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1521]
Follow-up to https://github.com/jbx-protocol/juice-interface/pull/1502#pullrequestreview-1048725183

- WDYT about hiding the form before the user has "Approved token for txn"? The user might fill out the form
- Does the whole page have to reload after the user "Approved token for txn"? If the tx succeeds, we can optimistically _assume_ that the "stake" tx will work. In other words, we can immediately update the UI when the "approve" tx succeeds.
-  There's a mixture of "stake" and "lock" terminology. Should we decide on one term?
- Move note about ERC-20 to the callout

**Comment by jmilldotdev** [comment]
I created #1575 and #1576 as quick fixes and made issues #1573 and #1574 for more substantial tasks. Gonna close this.
