### ISSUE TITLE
'Receive ERC-20' option in payment form doesn't give ERC-20 tokens on V2 projects

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1561]
## Summary

Title. Reproduced in Rinkeby /v2/p/1 and /v2/p/4417

## Steps to reproduce

1. Go to a V2 project with an issued ERC-20
2. Pay the project and check 'Receive ERC-20'

## What is the _current_ bug behavior?

Tokens received show as claimable

## What is the expected _correct_ behavior?

Tokens should not show as claimable

## Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/33093632/181129522-23b7affb-d286-43e9-97dc-b54a72538804.png)

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment]
Confirmed. `preferClaimedTokens` should be set to `true` when the checkbox is checked.

**Comment by tomquirk** [comment]
Also confirming it's a v2 only issue
