### ISSUE TITLE
Improve social links on mobile.

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1565]
Implement this design for social links on mobile.

![](https://user-images.githubusercontent.com/109319681/181177400-b9fcb05a-fb29-4f97-97ba-9b8fa0ba9416.png)

**Comment by strath-m** [comment]
Figma file here if needed for sizing / icons: https://www.figma.com/file/XEBCjxletE7rDdbj3Mk8lV/JBX---NFT-Rewards-UI---July-2022?node-id=0%3A1

**Comment by benschac** [comment]
Happy to grab this one @strath-m, could yah give me access to the figma?

**Comment by strath-m** [comment]
@benschac sweet, I invited you to the file. You can also try this Figma link: https://www.figma.com/file/XEBCjxletE7rDdbj3Mk8lV/JBX---NFT-Rewards-UI---July-2022?node-id=0%3A1
If that doesn't work let me know. (Updated social icons are on the screen in the bottom right, it that the title above 'Updated Social Icon Links Version' and I have left design comments on top)

**Comment by benschac** [comment]
https://www.figma.com/file/XEBCjxletE7rDdbj3Mk8lV/JBX---NFT-Rewards-UI---July-2022?node-id=76%3A1583
