### ISSUE TITLE
Loading projects page with search param in URL doesn't populate search bar

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#1566]
## Summary

Loading the project page with a url like `juicebox.money/projects?tab=all&search=juicebox` should populate the search bar with "juicebox" and run a search query automatically. Alas it does not.

## Steps to reproduce

1. Go to https://www.juicebox.money/projects?tab=all&search=juicebox
2. No search

## Environment

- **Device/OS**: [Mac]
- **Browser:** [Brave]

**Comment by midnight-madman** [comment]
This is closed by https://github.com/jbx-protocol/juice-interface/pull/1572
