### ISSUE TITLE
Cancelling transfer tx keeps loading state

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1581]
## Summary

<img width="859" alt="Screen Shot 2022-07-28 at 6 01 11 pm" src="https://user-images.githubusercontent.com/96150256/181453797-91c3ac01-81bc-42a1-a815-eb10038014ba.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by benschac** [comment]
I'm pretty sure I know what's up with this.  I can grab.

**Comment by johnnyd-eth** [comment]
Legend @benschac 🙏
