### ISSUE TITLE
Can't edit payouts using amounts

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1620]
## Description

In v2, if a distribution limit is infinite, we only allow payouts to be set by %ages.

But, if there is a fixed distribution limit, owners should be able to set payouts by %age OR amount. (See V1 edit payouts).

## Repro

1. locally on mainnet, go to http://localhost:3000/@jango. This project has a 4 ETH distribution limit
2. Click Edit payouts
3. Click on the first payout
4. Observe. Only the percentage slider is visible.

The **Amount** input field should also be visible.

**Comment by wraeth-eth** [comment]
Just leaving a note here, adjusting distribution split is impossible in edit payouts by design. edit payouts uses the set splits contract, which doesn't affect the dist limit, whereas reconfigure will allow for this
