### ISSUE TITLE
Improve "Projects" page responsiveness

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1622]
## Description

Projects page isn't great on mobile.

<img width="414" alt="Screen Shot 2022-07-31 at 6 15 25 PM" src="https://user-images.githubusercontent.com/12551741/182018217-17c7367b-81c3-4853-a7ba-81918103f9ee.png">

## Proposal

There's a few low-hanging fruit.
- make cards smaller
- hide some text
- etc

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by FiyinOdebunmi** [comment]
I can work on this if there is no one assigned to this yet.
