### ISSUE TITLE
NextJS router.push causes runtime exception

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1634]
## Summary

Introduced in https://github.com/jbx-protocol/juice-interface/pull/1555

Last good commit: `a31623ce01e3b1a0f2a2429e57c69492a5e5f8a6`

Fixed temporarily with https://github.com/jbx-protocol/juice-interface/pull/1631.

Discussion: https://discord.com/channels/775859454780244028/866040669712678942

## Steps to reproduce

1. `git checkout 99d2fdc40643d8ad2ff567e073f9d7969ecca816` (revert the revert)
2. Create a project
3. Wait for the tx success
4. Observe page redirection. A runtime exception should occur (see screenshot)

## Relevant logs and/or screenshots

![](https://cdn.discordapp.com/attachments/866040669712678942/1003534316267130930/Screen_Shot_2022-08-01_at_2.56.59_PM.png)

**Comment by wraeth-eth** [comment]
I have discovered that this is actually an issue as to where the network provider sits:

If the network provider is embedded in each page individually, upon switching pages (while a wallet is connected) it will fail. By adding it to the app level (_app.page.tsx), this solves it. See https://github.com/jbx-protocol/juice-interface/pull/1673
