### ISSUE TITLE
Owner percentage doesn't show on infinite distribution 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1733]
## Summary

<img width="516" alt="Screen Shot 2022-08-14 at 11 18 30 pm" src="https://user-images.githubusercontent.com/96150256/184538932-e9f5d702-edcc-415b-9f0d-3fc4de9acd84.png">

This shouldn't be blank. Should show 'Owner 100%' like reserved tokens

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by NakedFool** [comment]
> 

do you happen to remember which projects are affected by this? some projects I just checked now with infinite dist had owner percentage

**Comment by NakedFool** [comment]
@johnnyd-eth Is this now connected to this fix? https://github.com/jbx-protocol/juice-interface/pull/1806

**Comment by NakedFool** [comment]
Ignore above, just found that this project has that issue  - https://juicebox.money/@dcfcdao
Investigating issue.
