### ISSUE TITLE
Project descriptions don't render new lines

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1738]
## Summary

This is a regression. Project descriptions that include newlines aren't rendered correctly on the project page.

## Steps to reproduce

1. Go to https://juicebox.money/v2/p/163
2. Observe project description

Original text:
```
Support Etherfunk: A new way to interact with any smart contract on Ethereum 🪩. Funds will be used for Etherscan API usage and website hosting. 👇

GOAL: Raise 6 months of expenses.

COST BREAKDOWN:
- Etherscan API: $199/month
- Hosting costs: $20/month
```

Rendered text:

```
Support Etherfunk: A new way to interact with any smart contract on Ethereum 🪩. Funds will be used for Etherscan API usage and website hosting. 👇 GOAL: Raise 6 months of expenses. COST BREAKDOWN: - Etherscan API: $199/month - Hosting costs: $20/month
```

## What is the _current_ bug behavior?

Project description rendered without new lines.

## What is the expected _correct_ behavior?

Project description should include new lines.

## Relevant logs and/or screenshots

<img width="1093" alt="Screen Shot 2022-08-15 at 3 42 23 PM" src="https://user-images.githubusercontent.com/12551741/184585586-fd11bc88-10b5-4aa6-bc76-b535bcea502c.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment]
@wraeth-eth @johnnyd-eth can one of you guys pick this one up please?

**Comment by wraeth-eth** [comment]
✋
