### ISSUE TITLE
Downloading payments CSV sometimes fails

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1828]
## Summary

Getting this error intermittently: 
https://user-images.githubusercontent.com/96150256/186579263-e7e045ae-bd65-4c97-9111-348b7e642940.mp4

<img width="1137" alt="Screen Shot 2022-08-25 at 3 02 35 pm" src="https://user-images.githubusercontent.com/96150256/186579240-f095be5b-1162-4e03-bdd9-7671f8f9f468.png">
(I see subgraph I click @peripheralist 😅)

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by peripheralist** [comment]
It looks like the graph isn't indexed to chain head—can happen if our indexers get behind (though probably means a graph infra problem)

Though leave this open since we should handle this error better

**Comment by tomquirk** [comment]
Is this still an issue @peripheralist ?

**Comment by peripheralist** [comment]
this would have been caused by the subgraph getting delayed in indexing, and us trying to get data for a block that hasn't been indexed yet. will leave this open and double check that the UI handles cases like this, but pretty sure it's closeable
