### ISSUE TITLE
Improve and optimise transaction modal

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#1861]
## Description

We need to work to make sure all our modals are consistent for transactions

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by johnnyd-eth** [comment]
Was about to make an issue for this but I guess this issue will encompass **V1 distribution payouts/reserved tokens modals**:

https://user-images.githubusercontent.com/96150256/187105299-b13f34a6-9acd-4099-8acd-8439d2235a01.mp4

**Comment by wraeth-eth** [comment]
@johnnyd-eth I was only going to focus on v2

**Comment by johnnyd-eth** [comment]
> @johnnyd-eth I was only going to focus on v2

May as well get the V1 instances of `TransactionModal` tidy as part of this issue too though right? Or would it be better as a different issue

**Comment by wraeth-eth** [comment]
It depends what work needs to be done - I haven't had a chance to have a look at what needs to change. It can definitely be a part of this issue though
