### ISSUE TITLE
Use DM Mono in Web3-onboard

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1872]
We're loading a whole new font for web3-onboard (Sofia Pro). This decreases performance, and also makes the UI less cohesive.

Lets use DM Mono (same font as the rest of the site) for now

<img width="805" alt="Screen Shot 2022-08-30 at 9 46 34 AM" src="https://user-images.githubusercontent.com/12551741/187320945-f67e1486-d135-4450-96e1-d64836015767.png">

**Comment by wraeth-eth** [comment]
I opted away from DM Mono as it doesn't look very good on this form 😅

**Comment by tomquirk** [comment]
> I opted away from DM Mono as it doesn't look very good on this form 😅

https://github.com/jbx-protocol/juice-interface/pull/1874
