### ISSUE TITLE
[BUG] Should not show "handle already in use" warning when input value matches the project's current handle

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#189]
![image](https://user-images.githubusercontent.com/79433522/141600380-410354b9-b36d-4436-8749-5063e9839e4d.png)

**Comment by jnoh** [comment]
Working on this here: https://github.com/jbx-protocol/juice-interface/pull/242

**Comment by jnoh** [comment]
Addressed by https://github.com/jbx-protocol/juice-interface/pull/241
