### ISSUE TITLE
Hide token migration tab on settings page for V2 projects

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1903]
## Summary

<img width="500" alt="Screen Shot 2022-09-02 at 10 52 27 am" src="https://user-images.githubusercontent.com/96150256/188036248-83daa6e3-1cd1-43dc-b1c5-d865eb9bc75e.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment]
This is the expected behaviour
