### ISSUE TITLE
Front Page payment feed doesn't show v2 project handles

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#1912]
## Summary

<img width="590" alt="image" src="https://user-images.githubusercontent.com/33093632/188281456-17987e79-6a1a-4965-b774-cd0a1d0f3267.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by NakedFool** [comment]
Very odd issue, correct `projectId` is being passed to `useProjectHandle` but every handle that is returned is `undefined`

And for some reason `readContract` in `callContractRead` function is `undefined` as well.

I'm looking into this.
