### ISSUE TITLE
Add nuance to 'Upcoming' tab

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1929]
## Description

There's currently a UX gap in the Upcoming FC tab.

We need to distinguish between Queued FC (the config that is dubbed to take effect next FC) and LatestConfigured FC (the config that, if approved, will take affect).

## Proposal

TBA

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by wraeth-eth** [comment]
@tomquirk should we erode bug?

**Comment by tomquirk** [comment]
@wraeth-eth Mmm, it still is a bug imo. Its functionality that doesn't work as expected. Needs design this one. I will fill out description better-er.
