### ISSUE TITLE
[IDEA] Better enforce code formatting

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#193]
The project contains a .prettierrc file, and is meant to be formatted using Prettier. How can we make sure new contributors are guided to use the same formatting configuration?

**Comment by jnoh** [comment]
Addressed by https://github.com/jbx-protocol/juice-interface/pull/215

**Comment by aeolianeth** [comment]
@jnoh thanks again for working on this ❤️  Given #215, can we close this issue?
