### ISSUE TITLE
[Draft] [Parent] Improve the Safe experience

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1931]
## Description

Juicebox projects are mostly managed by Safes. I want to put forward a case for a tighter integration with Safe.

I think this makes sense for the following reasons:

- Juicebox transactions are complex. Raw JB transaction data is meaningless to a human.
- Juicebox transactions are contextual. They relate to the inner workings of a project
- Lack of transparency. A project's community has to go looking for Safe activity.

## Loose tasks

- [x] https://github.com/jbx-protocol/juice-interface/issues/1911
- [ ] Render rich previews of relevant transactions, like set splits, reconfigurations etc.
   - [ ] Render diffs between current state, and state of the transaction (e.g. "this payout was added")
- [ ] Allow multisig signers to sign transactions from within JB
- [ ] ...

## PR Breakdown

1. List, read-only, no preview. Link to tx in Safe. Only QUEUED txs
2. List HISTORY
3. Create rich previews, iteratively, for each type of transaction
4. Show approval status
5. Add signing.
6. Diffs

## UX

Very loose thoughts: a **safe** dashboard `/v2/p/:id/safe` (or maybe /v2/p/:id/owner)

Similar to the Safe UI in high-level UX.

- two tabs: Queue and History
- List Txs as collapsed accordions
- Clicking on the Tx reveals the rich diff

<img width="1214" alt="Screen Shot 2022-09-07 at 8 53 48 PM" src="https://user-images.githubusercontent.com/12551741/188866798-2e9536e8-7ae6-48c4-a562-4925d8572369.png">

<img width="1206" alt="Screen Shot 2022-09-07 at 8 54 39 PM" src="https://user-images.githubusercontent.com/12551741/188867056-d98bdc83-48f7-47a1-a20e-176ace9dd1c7.png">

**Comment by johnnyd-eth** [comment]
1. List, read-only, no preview (remove some stuff done already). Link to tx in Safe. Only QUEUED txs 
2. List HISTORY
3. Create rich previews, iteratively, for each type of transaction:
- reconfigure
- set payouts
- etc...

4. Show approval status 
5. Add signing (for people on Multisig)

6. Difs

**Comment by tomquirk** [comment]
Closing this for now.
