### ISSUE TITLE
Activity feed not using project handle 

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#1939]
JuiceboxDAO has a handle (`@juicebox`) but we're rendering `Project #1` in the feed. Should be `@juicebox`

<img width="617" alt="Screen Shot 2022-09-09 at 9 30 34 AM" src="https://user-images.githubusercontent.com/12551741/189245843-54e0029d-2d38-4cf1-9413-d2b4fc3dae3c.png">

**Comment by NakedFool** [comment]
Duplicado ser? https://github.com/jbx-protocol/juice-interface/issues/1912

I was working on this but then switched to https://github.com/jbx-protocol/juice-interface/issues/1926 to clear my head in the meantime

**Comment by jmilldotdev** [comment]
Whatever the solution is to #1912 would fix this also i assume

**Comment by tomquirk** [comment]
Thanks @NakedFool yep, totally a duplicate of https://github.com/jbx-protocol/juice-interface/issues/1912

Closing!
