### ISSUE TITLE
Reconfigure page modals don't show up within Gnosis app

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#1967]
## Steps to reproduce

1. Go to Gnosis safe which owns a Juicebox project
2. Go to apps -> Juicebox (should open Juicebox in the Gnosis window signed into the Gnosis wallet)
3. Go to your Juicebox page, reconfigure, try to reconfigure something
4. See modals don't appear:

https://user-images.githubusercontent.com/96150256/189799946-3f2fa0ee-856a-4d41-b509-f864d3066599.mp4

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment]
Going to assume this is no longer an issue.
