### ISSUE TITLE
[BUG] Project handle form input doesn't autofill the defaultValue

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#200]
![image](https://user-images.githubusercontent.com/79433522/142256754-4272bdb5-60c0-4e15-b307-5514adf3c085.png)

Even when this form has a value for the address, the form input will not populate it and requires the user to retype it.

**Comment by aeolianeth** [comment]
Fixed in https://github.com/jbx-protocol/juice-interface/pull/241
