### ISSUE TITLE
Top nav remains solid when modals are open

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#2000]
## Summary

<img width="1430" alt="Screen Shot 2022-09-17 at 2 46 28 pm" src="https://user-images.githubusercontent.com/96150256/190840987-cd8d4fba-9e7a-4288-baf6-8dc3201cd9a2.png">

Likely a z-index issue.

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by tomquirk** [comment]
Thanks @NakedFool !!!!
