### ISSUE TITLE
Standardize logging

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2010]
## Proposal

Create a `log` module. Requirements:

- disabled by default in production
- enabled by default in non-production
- have a way of enabling it via localstorage (DEBUG_MODE=1 or something)
   - add a `.debug()` method to the `jb` global window object `src/lib/juicebox.ts`
- Accepts 3 arguments
   - module - name of the place where it's being logged (like ComponentName, useHookName, etc.)
   - message - some message
   - data - an object containing anything 
- Logs have the following format:

```
<module>::<message> <data>
```

Example:

```js
log('ContractReader', 'read contract', { functionName: 'test', contracts })
```

Output
```
> ContractReader::read contract { functionName: 'test', contracts: { .. } }
```

**Comment by benschac** [comment]
Would using something like winston be a good fit: https://github.com/winstonjs/winston
