### ISSUE TITLE
[BUG] Link on FAQs is broken

### ISSUE THREAD

**Issue by mporracindie** [jbx-protocol/juice-interface#203]
**Describe the bug**
On the [homepage](https://juicebox.money/#/) under FAQs the second question `What does Juicebox cost?` has a link that does work.
https://juicebox.money/#/p/constitutiondaojuicebox

**Comment by mporracindie** [comment]
Here is the line to fix: https://github.com/jbx-protocol/juice-interface/blob/main/src/components/Landing/Faq.tsx#L22

**Comment by mporracindie** [comment]
My mistake but the bug is still there. {window.location.href} does not always point to `https://juicebox.money/`

**Comment by peripheralist** [comment]
fixed
