### ISSUE TITLE
BuiltForList Reference Links to Create page

### ISSUE THREAD

**Issue by Lmhazan** [jbx-protocol/juice-interface#2159]
## Description

A number of users click on the builtForList copy when on the homepage banner section. Would be an easy play to have that copy link to the beginning of the create project onboarding flow.

## Proposal

Add reference links to BuiltForList copy

## Screenshots

<img width="1438" alt="Screen Shot 2022-10-06 at 10 12 41 PM" src="https://user-images.githubusercontent.com/8061700/194452222-6d6df180-f5cc-4cf3-86b7-7d739a31a8e8.png">

**Comment by tomquirk** [comment]
CLosing this due to homepage redesign incoming
