### ISSUE TITLE
Make transactor notifications stick to top

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#2174]
## Description

Transaction notifications are in a fixed location on the page. When I am on a long form such as the project details form and i submit the transaction, I don't get a loader spinner on the button or any visual indication that something is happening until i scroll to top.

## Proposal

Would perhaps be a nicer UX if the transactor notification stack stuck to the top of the browser window

## Screenshots

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/33093632/194877969-e99ff9c9-bbef-4d29-99d0-fa620b0e40fb.png">

**Comment by jmilldotdev** [comment]
wyt @peripheralist

**Comment by peripheralist** [comment]
this would prolly be a better UX. though with the button to toggle the list in the navbar, it feels a little awkward to have to scroll up to hide the transactions. pulling the button out of the navbar is also a little tricky. but super open to some refinements if we wanna improve it
