### ISSUE TITLE
'In Treasury' may not account for distributions 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#2330]
## Summary

<img width="743" alt="Screen Shot 2022-10-24 at 9 37 34 am" src="https://user-images.githubusercontent.com/96150256/197423823-f85f26e2-3a23-400d-9d15-a03f09ee4391.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by peripheralist** [comment]
ty 🙏 this will be fixed in next publish
