### ISSUE TITLE
Holders list and Manage tokens section disagree

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#2333]
## Summary

<img width="705" alt="Screen Shot 2022-10-24 at 9 43 57 am" src="https://user-images.githubusercontent.com/96150256/197424098-27fa39e0-af3e-41bf-864a-3671d8366455.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by jmilldotdev** [comment]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/33093632/197435584-82a7eb49-d773-4a16-9ad9-c6e2a0f2fe9a.png">

can confirm this is issue is at the subgraph layer, is one of those 'experimental data index failures'

**Comment by jmilldotdev** [comment]
query:

```
query {
  participants (where: {
    projectId: 256,
    cv: "2",
    wallet: "0x0cf18d21209ef4d0e603e15fb51c8a6d6cb49c6d"
  }) {
    wallet
    totalPaid
  }
  payEvents (where: {
    projectId: 256,
    cv: "2",
    caller: "0x0cf18d21209ef4d0e603e15fb51c8a6d6cb49c6d"
  }) {
    amount
  }
}
```

**Comment by johnnyd-eth** [comment]
Legend @jmilldotdev, will flick this to @peripheralist for a look

**Comment by peripheralist** [comment]
oof. thanks @nnnnicholas , could you share the actions you've taken with the tokens to help debug?

**Comment by nnnnicholas** [comment]
Hey sry just saw this!

Yes iirc I just moved the unclaimed tokens out of the wallet that minted them, and yet they still show up in the Holders list.

**Comment by tomquirk** [comment]
cc @peripheralist is this still an issue or something worth fixing? if not lets clsoe it

**Comment by peripheralist** [comment]
yep this was fixed, closing
