### ISSUE TITLE
Project ID is no longer shown anywhere in the frontend for projects with handles

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#2339]
## Description

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/33093632/197432345-e0c38629-549a-4824-895b-c27433864912.png">

There used to be a project ID display next to the vX selector in the project header actions. We should re-add it, or otherwise display what a project's ID is.

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by tomquirk** [comment]
@jmilldotdev its on the hover state of the project handle.
