### ISSUE TITLE
[BUG] Adding a payout without wallet address confirmation shouldn't be possible

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#234]
**Describe the bug**
It's currently possible to save a payout without waiting for the wallet address to be loaded.

The results in a payout being saved with no wallet address, which shouldn't be possible.

https://user-images.githubusercontent.com/94939382/143668173-b1516e0b-dec4-4749-8a06-b5c249127046.mp4

**Expected behavior**
At minimum, we should show a loading spinner (or similar) in the **Address** field to indicate to the user that something is happening.

Ideally, I think we should make **Address** a required field.

**To Reproduce**
1. Navigate to the Distribution section of project creation
2. Select **Add a payout**
3. Enter a valid wallet address and immediately select **Ok**
4. Observe. The payout is saved with no wallet address

**Setup (please complete the following information):**
 - Device/OS: MacOS
 - Browser: Brave
 - Hardware wallet: nil

**Comment by peripheralist** [comment]
fixed
