### ISSUE TITLE
[BUGish] Don't hide "Claim" button when no tokens are claimable

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#235]
**Describe the issue**
We currently hide the “claim” button if people don’t have any tokens to claim. This is causing confusion:
https://discord.com/channels/775859454780244028/866040669712678942/913538871508226079

**Proposed solution**
Always show the "claim". When no tokens are claimable,  disable the button and show a tooltip on hover explaining why it's disabled.

**Screenshots**
![](https://cdn.discordapp.com/attachments/866040669712678942/913146784585490462/unknown.png)

**Comment by peripheralist** [comment]
done
