### ISSUE TITLE
Awkward label when no limit distribution is set

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#2353]
## Description

<img width="501" alt="image" src="https://user-images.githubusercontent.com/33093632/197609794-9aedd092-e6b0-4057-8119-0deb2829e427.png">

`0/NO LIMIT distributed` is kinda awkward, should handle this differently. Maybe remove `/NO LIMIT`, or otherwise indicate there is no distribution limit.

**Comment by jmilldotdev** [comment]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/33093632/197671658-4b52ded5-f200-404b-9bb8-2053aca65924.png">

it looks like we're setting a large value for `distributionLimit` when we have no limit, hmm

**Comment by peripheralist** [comment]
> <img alt="image" width="607" src="https://user-images.githubusercontent.com/33093632/197671658-4b52ded5-f200-404b-9bb8-2053aca65924.png">
> 
> it looks like we're setting a large value for `distributionLimit` when we have no limit, hmm

for "no limit" the UI just sends the maxInt value, so "no limit" is really "infinite" and not the same as "limit = 0"

**Comment by peripheralist** [comment]
also linking feedback here https://github.com/jbx-protocol/juice-interface/pull/2359#issuecomment-1291448428

**Comment by tomquirk** [comment]
Is **unlimited** a possibility?
