### ISSUE TITLE
Fix i18n.loadLocaleDate console error

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2391]
## Description

There is this error.

```
Plurals for locale undefined aren't loaded. Use i18n.loadLocaleData method to load plurals for specific locale. Using other plural rule as a fallback.
```

It's fixed by calling `activateDefaultLocale()` outside of the component scope (so, on JS module execution). But, doing so breaks the rest of the site :(

**Comment by benschac** [comment]
I was looking into this the other day, going to grab it.
