### ISSUE TITLE
Payouts seem to be taking terminalV1.fee() into account instead of FC.fee() [BUG] 

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-interface#249]
**Describe the bug**
Funding cycle payouts should not use TerminalV1.fee() in their calculation, this is inaccurate. Instead they should use the fundingCycle.fee property in the struct.

**To Reproduce**
juiceboxDAO project Dash.
![image](https://user-images.githubusercontent.com/77952627/144261917-8bf4e086-0a8a-4949-b792-5b4ec6d6866f.png)

**Setup (please complete the following information):**
brave

**Comment by mejango** [comment]
Also ENS names dont seem to be resolving rn.

**Comment by mejango** [comment]
This is unlike the reconfiguration page, where the TerminalV1.fee() must be taken instead of the current funding cycle's fee.

**Comment by peripheralist** [comment]
fixed
