### ISSUE TITLE
[IDEA] Disclose a token's AMM price(s)

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#258]
How might we disclose a Token’s AMM price(s) on the dashboard so users can make the most informed decisions when considering a contribution? Perhaps this is something addable in a project’s metadata?

Raised in: https://discord.com/channels/775859454780244028/786985806396784690/917154545560330340

**Comment by peripheralist** [comment]
docs for fetching pair price on Uniswap: https://docs.uniswap.org/sdk/guides/fetching-prices

for pair price on Sushi, looks like we can do `SushiV2Factory.getPair()` https://dev.sushi.com/sushiswap/contracts

i'd be down to support both exchanges, and show one or both prices depending on if a pair exists on that exchange

**Comment by aeolianeth** [comment]
Sweet thanks for the links. I'm keen to take this one 👍

**Comment by peripheralist** [comment]
hey @aeolianeth, i have a WIP prototype here https://github.com/jbx-protocol/juice-interface/pull/267 for showing redeem + pay as tabbed UI elements in the same section. But to do it well there needs to be some pretty significant reorganization of components, so to avoid messiness with merge conflicts I'm delaying finishing this until the v1.1 goes live. But feel free to build off this branch! I think it'd be great to solve both of these things together.

**Comment by aeolianeth** [comment]
> hey @aeolianeth, i have a WIP prototype here #267 for showing redeem + pay as tabbed UI elements in the same section. But to do it well there needs to be some pretty significant reorganization of components, so to avoid messiness with merge conflicts I'm delaying finishing this until the v1.1 goes live. But feel free to build off this branch! I think it'd be great to solve both of these things together.

Oh nice @peripheralist, looks great. Hope you don't mind me dropping some screenshots in #267's description for my future reference https://github.com/jbx-protocol/juice-interface/pull/267#issue-798403194.

**Comment by aeolianeth** [comment]
I think the main challenge here is the UX. As @mejango has mentioned, we don't want to blatantly advertise a particular AMM; our goal is simply to reduce information asymmetry. I'm hoping to have some time in the next few days to get some clear ideas down in mockups 👍

**Comment by peripheralist** [comment]
I don't mind specifically supporting Uniswap/Sushiswap/both. Our choice of supported AMMs can be arbitrary to start off with—if the community were to pressure us to support other AMMs, we'd be open to it.

**Comment by aeolianeth** [comment]
Closing this issue!

Sushiswap coming in https://github.com/jbx-protocol/juice-interface/issues/344
