### ISSUE TITLE
[Parent] UI polish

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2609]
- [x] https://github.com/jbx-protocol/juice-interface/issues/2608
- [x] https://github.com/jbx-protocol/juice-interface/issues/2607
- [x] https://github.com/jbx-protocol/juice-interface/issues/2605
- [x] https://github.com/jbx-protocol/juice-interface/issues/2604
- [x] https://github.com/jbx-protocol/juice-interface/issues/2593
- [x] https://github.com/jbx-protocol/juice-interface/issues/2592
- [x] https://github.com/jbx-protocol/juice-interface/issues/2591
- [x] #2610
- [x] #2611
- [x] #2613
- [x] #2615
- [x] #2618
- [x] #2620
- [x] #2624
- [x] #2637
- [x] #2640
- [x] #2646
- [x] #2649
- [x] #2693

**Comment by peripheralist** [comment]
ooooh is this done now?

**Comment by NakedFool** [comment]
@peripheralist it is, let's close it! 🍻
