### ISSUE TITLE
Image sizes from IPFS on production are huge

### ISSUE THREAD

**Issue by benschac** [jbx-protocol/juice-interface#2669]
## Summary

<img width="1725" alt="CleanShot 2022-12-08 at 21 53 09@2x" src="https://user-images.githubusercontent.com/2502947/206613613-6e9c6617-9926-444b-8d92-bb50113bc252.png">

The end user is downloading something like 3MB from pinata / ipfs

I have a PR addressing this shortly
## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by benschac** [comment]
Did a bit more research here. 
Problem: load a giant file on a payment. Any user who hits `landing` will endup downloading the entire file which will result in a slower load time and probably a higher IPFS/Infura bill.

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/2502947/207071611-9971fc0f-0462-47bb-ad74-9b41a029452a.png">

Pinata has an image optimization product / feature. 

docs: https://docs.pinata.cloud/gateways/image-optimization#pinata-image-optimization and I implemented it in this PR: 
https://github.com/jbx-protocol/juice-interface/pull/2679

this could be out dated but, it doesn't seem like there's anyway to resize images directly from IPFS.

https://community.infura.io/t/ipfs-gateway-image-optimization/5487

also noticed we're nixing pinata everywhere so it doesn't matter: https://github.com/jbx-protocol/juice-interface/pull/2687/files



I did see a solution with cloudflare workers that looked promising: https://developers.cloudflare.com/images/image-resizing/resize-with-workers


wyat @tomquirk

**Comment by tomquirk** [comment]
Closing this for now as its low prio
