### ISSUE TITLE
[This tool is amazing, why dont deploy it in all the big EVM´s?] 

### ISSUE THREAD

**Issue by adaig** [jbx-protocol/juice-interface#2738]
## Description

[This tool is amazing, why dont deploy it in all the big EVM´s?] 

## Proposal

Deploy the contracts in all the bigs EVM chains

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by tomquirk** [comment]
Coming soon maybe! Keep an eye on this Discord thread: https://discord.com/channels/775859454780244028/969921228435501076
