### ISSUE TITLE
Fix resetting project handles that contain emojis

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2758]

**Comment by wraeth-eth** [comment]
Can I grab some more info on this one?

**Comment by wraeth-eth** [comment]
I think https://github.com/jbx-protocol/juice-interface/pull/2889?no-redirect=1 might close this but im not sure what the nature of this ticket is @aeolianeth

**Comment by wraeth-eth** [comment]
@tomquirk do you mind testing this one against latest branch to see if it is still a recurring issue?

**Comment by tomquirk** [comment]
im guess this is done tbh
