### ISSUE TITLE
Add ability to link to payments

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2765]
As an MVP:
1. click on payment somehow (share button?)
2. Link copied to clipboard and added to URL bar as a hash route (juicebox.money/@juicebox#payment_xyz
3. Visually indicate this somehow (outline on the payment? slightly shaded background color?)

When landing on a payment:
- auto-scroll to payment
- visually indicate selection

**Comment by wraeth-eth** [comment]
This is definitely non-trivial :(

I wouldn't bring this one into current sprint unless you think it is paramount to goals. Either that or maybe need to be reassigned. wdyt @tomquirk ?

**Comment by tomquirk** [comment]
ya its a biggie. I really do think we should prioritize it though.

Ive updated description with what i think could be mvp. Don't think this would be thaaaat big of a lift.

**Comment by wraeth-eth** [comment]
There is some stuff to consider though. The big one that comes to mind is pagination id and how we load history etc.

We can definitely get recent txs easy, but its the older more buried ones that will be a problem (and these will exist as people share tx)

We also need to consider wha the ograph and other SEO of those links should look like. We probably want to make them the focus of their SEO

**Comment by wraeth-eth** [comment]
I think this is like 2 weeks of work tbh

**Comment by tomquirk** [comment]
@wraeth-eth sorry i probably wasn't explaining well enough what i was thinking for MVP.

This is all it is: https://github.com/jbx-protocol/juice-interface/pull/2978/files

- clicking on a payment TS appends a hash to the URL
- add an ID to the DOM element so that the browser knows to auto-scroll
- add some logic to keep paginating thru activity feed until the selected item is included

Using that as a base, we can do the fancy stuff later (better OG, styling etc.)

**Comment by wraeth-eth** [comment]
Yeah that sounds GTM!
