### ISSUE TITLE
Redemption rate set to 100% when funding target is set to infinite

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#2777]
## Summary

When setting the funding target to infinite, the system is automatically setting the redemption rate to 100%. This is not the expected behavior and can cause confusion for users.

## Steps to reproduce

1. Navigate to the funding target settings
2. Set the funding target to infinite
3. Observe that the redemption rate is automatically set to 100%

## What is the expected _correct_ behavior?

The redemption rate should not be affected by the funding target setting. It should remain as set by the user.

## Discord Link

https://discord.com/channels/775859454780244028/866040669712678942/1057159899462783047

**Comment by tomquirk** [comment]
did this get done?
