### ISSUE TITLE
Disable text selection inside the NFT Div

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#2781]
## Summary

It is possible to select text inside the NFT div, which causes confusion and is not expected behavior. It might be good to disable text selection inside the NFT div to improve user experience.

## Steps to reproduce

1. Navigate to any project with nft rewards
2. Attempt to select text inside the div
3. Observe that text can be selected

## What is the expected _correct_ behavior?

Text selection inside the NFT div should be disabled to improve user experience and avoid confusion.

## Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/104132113/212572766-7d81f626-d2b8-4d28-995e-cbc9b00f4bbb.png)

## Discord Link

https://discord.com/channels/775859454780244028/866040669712678942/1063569466136461444

**Comment by johnnyd-eth** [comment]
Discussion: https://discord.com/channels/939317843059679252/1037874587444183171/1064364043323854868
