### ISSUE TITLE
Font size on v1 activity feed for primary number is incosistent

### ISSUE THREAD

**Issue by NakedFool** [jbx-protocol/juice-interface#2790]
## Summary

Distributed Funds number is smaller than Distributed Reserved Tokens number.

## Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/18723426/212687313-4511de8d-90ba-409e-ace4-037e7dd2fca2.png)

## Discord link
https://discord.com/channels/775859454780244028/1064375393026588713/1064375397287985182

**Comment by tomquirk** [comment]
fixed in https://github.com/jbx-protocol/juice-interface/pull/2797
