### ISSUE TITLE
Come up with better design for project card tooltips

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2799]
This sucks

<img width="622" alt="Screenshot 2023-01-17 at 1 13 02 PM" src="https://user-images.githubusercontent.com/12551741/212798257-45189cf1-2a87-4a2b-a348-81d45e33183f.png">

**Comment by wraeth-eth** [comment]
Can we just remove these?

**Comment by tomquirk** [comment]
@wraeth-eth yeah i think so for now👍
