### ISSUE TITLE
Investigate seo issues

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#2809]
Watch this https://www.loom.com/share/606aba0deaf04734afc13bd6a2b0edab

**Comment by wraeth-eth** [comment]
@tomquirk I think it is still an issue. Disabling JavaScript still returns nothing. How do you feel about upgrading this from 3 to 2 (or even 1)?

**Comment by tomquirk** [comment]
ya it's not the JS disable that an issue; the google crawler still knows about JS. Its just that the meaningful content needs to load before the crawler gives up.

Indexing has improved since making the change: https://discord.com/channels/775859454780244028/1064616063364518059/1066901975293235200

I think we can close this and await more feedback from Vis team.

**Comment by wraeth-eth** [comment]
I still think we need to reflect a ticket in our backlog for getting SSR working - wdyt @tomquirk
