### ISSUE TITLE
Cant add new nor change existing payout

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#2851]
## Summary

KMac reported that they are unable to change the Distribution limit for Goerli project 399 and 401. They expected to be able to edit the existing payout amount but were unable to do so. The messages says "required" no matter what amount or percentage entered.

## Steps to reproduce

1. Click "Funding"
2. Select "Amounts" option under Payouts
3. Attempt to change the Distribution limit for Goerli project 399 and 401

## What is the _current_ bug behavior?

The Distribution limit for Goerli project 399 and 401 does not change and the messages says "required" no matter what amount or percentage entered.

## What is the expected _correct_ behavior?

The Distribution limit for Goerli project 399 and 401 should change to the desired amount

## Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/104132113/213943893-f650a3bd-82fd-4560-9eac-def5211e136d.png)

## Notes

- By default, all funds are routed to the project owner and the distribution limit cannot be changed.
- If a payout to a different address is added, then the project owner will receive the remaining amount (if any).
- The reconfiguration UX needs a lot of love.

## Discord Link

https://discord.com/channels/775859454780244028/1066519755051257997

**Comment by tomquirk** [comment]
think this is good now.
