### ISSUE TITLE
Inconsistencies and unclear behavior in NFT tier management

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#2853]
## Summary

Nicholas reported several issues when trying to manage NFT tiers. Gabriel's first batch of NFTs has sold out and Nicholas is adding new NFTs to the collection. However, when inspecting details for the previous, sold out NFTs, the Limited Supply toggle is deselected, causing confusion about whether there will now be unlimited NFTs of these two sold out tiers, or if they will remain sold out. Additionally, it is unclear if it is possible to increase total supply of a tier post-facto. Another issue is that it is unclear what happens when clicking "Delete NFT." Is the user deleting the tier (and NFTs already minted) or just removing it from sale?

## Steps to reproduce

1. Sell out a batch of NFTs
2. Add new NFTs to the collection
3. Inspect details of the sold-out NFTs
4. Try to increase total supply of a tier
5. Try to delete an NFT

## What is the _current_ bug behavior?

1. The Limited Supply toggle is deselected and it is unclear what will happen if the user deploys as-is.
2. It is unclear if it is possible to increase total supply of a tier post-facto
3. The user is unsure what happens when they click "Delete NFT"

## What is the expected _correct_ behavior?

1. The Limited Supply toggle and value should remain the same as when the NFTs were originally set.
4. The user should be able to increase total supply of a tier if they choose to
5. The user should know what will happen when they click "Delete NFT" and it should be clear whether they are deleting the tier or just removing it from sale.

## Notes

- Every time the "Add NFT details" view is closed, the limited supply toggle is deselected
- Tiers can't be edited.
- Deleting from the UI will likely remove the tier from the contract
- UI should distinguish between deleting tier for sale (aka view function) vs deleting tier from contract (not possible)
- UI should show sold-out NFTs at the bottom for social proof.
- There is a need for a subgraph work to make the UI access NFTs through it instead of contract, which will allow more creativity
- When clicking details view on a new tier, it is showing the image of the old tier (which was deleted)
- When adding 2 tiers, then deleting two old tiers in a separate tx, the UI does not load the NFTs anymore and NFT settings are blank.

## Discord Link

https://discord.com/channels/775859454780244028/1066013675401510994

**Comment by johnnyd-eth** [comment]
(mostly solved in #2866, rest of the issue has been added to #2867)
