### ISSUE TITLE
Cannot set Goerli ENS Name Handle for Project

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#2892]
## Summary

When attempting to set a Goerli ENS Project Handle, it doesn't appear to work.

This includes both when using the project setting steps, and setting a ENS Name for `juicebox_project_id` directly on the ENS website.

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

## Discord Links

https://discord.com/channels/939317843059679252/939705688563810304/1068405025988169748

https://discord.com/channels/775859454780244028/942522503258054686/1068969176816963718

**Comment by tomquirk** [comment]
Linked to https://github.com/jbx-protocol/juice-interface/pull/2960

@wraeth-eth is this still an issue for you?

If not, perhaps we can close this and @peripheralist create another issue for https://discord.com/channels/939317843059679252/939705688563810304/threads/1071879192221859921 ?
