### ISSUE TITLE
App should prompt user to switch network of their connected wallet when on the wrong network

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#290]
## Description

When going to juicebox.money (mainnet) or rinkeby.juicebox.money with the connected wallet using the wrong network, a modal is displayed telling the user to switch networks.

## Proposal

This would be a smoother experience if the app prompted the user to switch their connected wallet's network, and refreshed automatically whenever the network is switched.

Additionally, if a user switches their network with the app open, the app could automatically redirect to the app on the correct network.

**Comment by johnnyd-eth** [comment]
Hey @peripheralist, love this idea and keen to start working on it tomorrow. Were you thinking of just showing the modal when the user connects to their wallet (and they're on the wrong network)? Also, would the modal have any functionality (other than automatically closing when the user changes to the right network) or would it just have an 'OK' button to close it?

**Comment by peripheralist** [comment]
@johnnyd-eth if the user connects their wallet and they're on the wrong network, i'd love for the modal to pop up with a button to "switch network to <network>", which then switches the network in the connected wallet i.e. metamask. 

i haven't looked into what's involved in doing that, so happy to follow whatever ideas you come across!
