### ISSUE TITLE
Update NFT page with new UI

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#2901]
## Summary

You can click next without filling out both required. This should be rethought

Design: https://www.figma.com/file/EN7CZTekcSo3sHyaGt6cC0/JBX---Project-Creation-Flow---High-Fidelity---Updated-Jan-2023?node-id=3285%3A163287&t=zTZOrZQKv7M1QqcJ-1

Thread: https://discord.com/channels/939317843059679252/1068601323475456051/1069477650432806973

**Comment by wraeth-eth** [comment]
https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro3nySutAgQPt34lNFAjvKx18J6EtfN0IydFNhmyIvmzCHOPswZDDC9HiJ1xNZRSYE9To7oxVzXsvtVXueE8Z8gTCRc6kN-2FCM6PVaZBpbm55gqES-2BFFa2vuOlTmTHBc8zkxiwwOi9wFpsgN82tmG6gy4-3DK5Vv_uLUa1W0cH0Aq-2BecF6inFavBFSDG891nrsrNm5Y6aeClkX5dN5OlXf2pjGcbNjCkbYqH5t2B7Ea9u6ivNmdHrjhd-2FrnmqA6s-2F3r1rbQU9fTGYZ8DHbnlMee8riC6Jq9LhVW-2Bfu35N-2BPL4s1K4qDLMCV-2FA0Ueu4LiJp2nEzFMT3cCuh4rH0z-2F1ZgonHfM1Gj2aLjNfBHy-2Fw59S0pPezYem8zEWDnWUJy0uwNYRQZDsVHZHTgTEdE0aqjSjkjN309yK

**Comment by tomquirk** [comment]
@wraeth-eth maybe can bundle this in here too: https://github.com/jbx-protocol/juice-interface/issues/2775

**Comment by wraeth-eth** [comment]
> @wraeth-eth maybe can bundle this in here too: #2775

sounds good to me @tomquirk what do you think is a reasonable increase?

**Comment by wraeth-eth** [comment]
cc @nnnnicholas re individual NFT description size increase

**Comment by wraeth-eth** [comment]
bump @tomquirk @nnnnicholas re NFT description size

**Comment by nnnnicholas** [comment]
> sounds good to me @tomquirk what do you think is a reasonable increase?
Maybe 10k characters? Doesn't cost us much and never know how someone might want to use that space.
