### ISSUE TITLE
[BUGish] Display edit-related text when editing reserved token receiver

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#292]
## Description

Currently the 'Add token receiver' modal is being displayed when editing a reserved token receiver. 

## Proposal

Change this to display edit-related text

## Screenshots

<img width="632" alt="Screen Shot 2021-12-18 at 2 31 16 pm" src="https://user-images.githubusercontent.com/96150256/146628949-3b0dee4c-b853-4675-b057-94b7eee69396.png">
<img width="940" alt="Screen Shot 2021-12-18 at 2 31 38 pm" src="https://user-images.githubusercontent.com/96150256/146628953-20c483e4-46a9-48d5-ab1a-f940b73c533c.png">

**Comment by peripheralist** [comment]
nice catch! Changing the title to "Edit token receiver" and button to "Save token receiver" would be great.

**Comment by peripheralist** [comment]
fixed by https://github.com/jbx-protocol/juice-interface/pull/293/files
