### ISSUE TITLE
[9] Consolidate Funding Target & Payouts pages in create flow

### ISSUE THREAD

**Issue by strath-m** [jbx-protocol/juice-interface#2938]
Removes 'Funding target' page and Consolidates with the Payouts page for closer parity with contracts and overall better UX.

![Image](https://user-images.githubusercontent.com/109319681/217744118-fc6bbb8e-5f04-4692-9d22-a094ecaf2031.png)

RICE:
R – 3
I – 3
C – 2
E – 2

Score: 9

**Comment by tjl-me** [comment]
This keeps causing bugs and needs to be done asap.

**Comment by strath-m** [comment]
@wraeth-eth this is ready for dev. Handover call done today 9/02/2023. Please LMK if you have any other questions.

To note: there may be very minor copy changes but overall design as you see it will remain the same.

Figma file here:
https://www.figma.com/file/EN7CZTekcSo3sHyaGt6cC0/JBX---Project-Creation-Flow---High-Fidelity---Updated-Jan-2023?node-id=3647%3A182519&t=0oV7woanrRY0ngwa-1

**Comment by strath-m** [comment]
Update: Dark Mode in progress (will be extremely similar to what we have now)

**Comment by strath-m** [comment]
@wraeth-eth Mobile Screens done and in that figma file. Reach out if you have any questions.

**Comment by wraeth-eth** [comment]
What is the process for handover here? Do I assume ownership of this issue, or create a new one? @tjl-me

**Comment by wraeth-eth** [comment]
(Assigning myself purely for tracking purposes)

**Comment by tjl-me** [comment]
@wraeth-eth good question.

When @strath-m hands over via comments, @strath-m should remove himself as assignee, add you as assignee and move into 'ready for dev' column. I'm still working through some changes but will be grooming on behalf of for a while.
