### ISSUE TITLE
[1] Failed transaction for buy 'project token' on Goerli

### ISSUE THREAD

**Issue by tjl-me** [jbx-protocol/juice-interface#3020]
User encountered an issue when trying to 'buy' a project token on Goerli.

**Error message:**
Transaction failed
invalid arrayify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.5.0)

**Discussion thread:** 
https://discord.com/channels/775859454780244028/864240636277293106/1073645695619309689

RICE:
R – 1 //only applies to people that are testing project creation on Goerli
I – 1 //issue doesn't prevent any contributions or projects being created in prod
C – 1 //unsure about how many creators create projects on Goerli before creating in prod
E – 1 //relatively small fix and change

Score:
1

**Comment by tomquirk** [comment]
@tjl-me this ended up bring a critical bug where payments for non-NFT projects were broken (goerli and mainnet).

Fixed tho, so closing!
