### ISSUE TITLE
[8] Project Page Redesign

### ISSUE THREAD

**Issue by tjl-me** [jbx-protocol/juice-interface#3030]
Redesign Project Page with a focus on conversion.

### RICE Score

Reach=4
Impact=3
Confidence=2
Effort=3

**Score: 8**

### Subtasks

- [x] User Research
- [ ] Wireframes
- [ ] Screen Designs
- [ ] Prototype Usability Testing
- [ ] Technical Scoping
- [ ] Dev
- [ ] Usability Testing/QA

**Comment by strath-m** [comment]
Project page user interview recordings, notes and key takeaways are now here in the Frontend Notion: https://juicebox.notion.site/Project-Page-User-Testing-Feb-2023-6ac3756d3e8041a1bc14fad9513bc304
