### ISSUE TITLE
[6] Error 404 on 'contact contributor' in project creation flow

### ISSUE THREAD

**Issue by tjl-me** [jbx-protocol/juice-interface#3059]
When creating a project, there is a button at the bottom that allows you to contact a contributer for additional support/help. This is currently displaying an error 404.

Screenshot:
![Image](https://user-images.githubusercontent.com/124005990/219831576-a744c11b-f68a-4f5c-96bf-781cabcccb87.png)

R-2
I-1
C-3
E-1
Score: 6

**Comment by tomquirk** [comment]
closing as we think its resolved, but can reopen if it resurfaces 🙏
