### ISSUE TITLE
V1 activity CSV exports are broken

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#3090]
## Summary

Activity feed CSV exports on V1 don't include any data. Only the heading row is included in the downloaded csv file.

## Steps to reproduce

1. Go to https://juicebox.money/p/moondao
2. Click on the Download button (next to **Activity**)
3. Download any csv type
4. Observe. No data

## What is the _current_ bug behavior?

Activity feed CSV exports on V1 don't include any data.

## What is the expected _correct_ behavior?

Activity feed CSV exports on V1 should include the expected activity data.

**Comment by filipviz** [comment]
Fixed
