### ISSUE TITLE
See Juicebox from any account

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-interface#31]
I'd like to be able to view Juicebox projects as any address

**Comment by nervetrip** [comment]
Can you clarify this issue, I'm not sure what you mean?  When I connect via different addresses in MM, I can see all projects on the juicebox.money site.

**Comment by mejango** [comment]
Yeah, I mean any other public address. Without having to connect. I can just punch in your address and see the project page from your perspective.

**Comment by mejango** [comment]
This would be really useful for TileDAO, @peripheralist's project, right now. The DAO has been investing in Juicebox, and gets JBX in return. Itd be great for anyone to view JuiceboxDAO from the perspective of the TileDAO contract to see their balance.

**Comment by jmilldotdev** [comment]
Can't a user achieve this with something like https://impersonator.xyz now?

**Comment by jmilldotdev** [comment]
@mejango close?

**Comment by mejango** [comment]
clothes
