### ISSUE TITLE
Reserved token splits can sum to more than 100%

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#3108]
## Summary

Should not let me save in the modal if the new split makes the total split percentage > 100%

<img width="568" alt="Screen Shot 2023-02-28 at 2 41 26 pm" src="https://user-images.githubusercontent.com/96150256/221756591-a83e21fc-784c-40c6-8484-dfa1460a6b71.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by Arun89-crypto** [comment]
Hey @johnnyd-eth 
Can you please assign this bug to me. I will fix it.

**Comment by Arun89-crypto** [comment]
Hey @filipviz 
Do I have to create and register my own project in order to recreate the bug ?

**Comment by filipviz** [comment]
Hi @Arun89-crypto

To recreate the bug, you can go to [juicebox.money/create](https://juicebox.money/create), navigate to the Token tab, select "Custom token rules", and then add wallets to the reserved token recipient list:

![image](https://github.com/jbx-protocol/juice-interface/assets/96905094/ae3167fe-01f2-4829-a69e-ba911c448223)
