### ISSUE TITLE
Add a risk disclosure to the top of the home page

### ISSUE THREAD

**Issue by mejango** [jbx-protocol/juice-interface#32]
"The Juicebox contracts have not been formally audited, use at your own risk. The community that supports Juicebox can be found and <link to discord>"

**Comment by mejango** [comment]
I think is actually p important @peripheralist

**Comment by aeolianeth** [comment]
@mejango following up here - do you think this disclosure is sufficient? https://github.com/jbx-protocol/juice-interface/issues/32#issuecomment-906641665
