### ISSUE TITLE
[IDEA] Add tooltips with timestamp to every time-related component

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#330]
## Problem to solve

Relative times are great, but sometimes it's helpful to know the timestamp.

## Proposal

A tooltip on every time-related UI element (e.g. relative times and absolute times).
This would probably come in the form of a `Time` component.

**Comment by peripheralist** [comment]
which components are you thinking of? for onchain events, there are links to etherscan so users could always check the transaction itself (though not the smoothest UX if you're doing that a lot)

**Comment by aeolianeth** [comment]
These are the ones that I'd immediately go for:

| location | screenshot |
| --- | --- |
| FC config | <img width="226" alt="Screen Shot 2022-01-08 at 11 01 43 am" src="https://user-images.githubusercontent.com/94939382/148626338-99658e98-b3b2-4129-8ed7-8256a13b7efa.png"> |
| FC banner | <img width="498" alt="Screen Shot 2022-01-08 at 11 01 24 am" src="https://user-images.githubusercontent.com/94939382/148626345-31c3218f-a30c-4a80-9c24-1149f424f547.png"> |
| activity feed | <img width="529" alt="Screen Shot 2022-01-08 at 11 00 50 am" src="https://user-images.githubusercontent.com/94939382/148626353-03849327-6489-4ac7-bfcc-d32255934443.png"> |

It could be a browser-native tooltip, like GitHub does:

<img width="276" alt="Screen Shot 2022-01-08 at 11 03 27 am" src="https://user-images.githubusercontent.com/94939382/148626375-b06ef2fe-12e5-46fd-8bc8-4802a97e0f6c.png">
