### ISSUE TITLE
[IDEA] Add "copy to clipboard" button on every address tooltip

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#331]
## Problem to solve

Copy-pasting wallet/contract addresses is a common action in Web3. Currently, a user has to manually highlight the wallet address text to copy it. This is slightly inconvenient and is error-prone.

## Proposal

Add a "copy to clipboard" button whereever we have tooltips for wallet addresses. Some (all?) addresses ahve tooltips with a link to etherscan - a small "copy to clipboard" button next to that might work well.

**Comment by peripheralist** [comment]
great suggestion. i've gotten so used to copying addresses manually that i hardly think of it anymore.

adding a copy button next to the etherscan link in the `FormattedAddress.tsx` component would work great
