### ISSUE TITLE
[IDEA] Limit file size for image uploads

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#332]
## Problem to solve

Project logos can be of any file size. This puts a burden on the users browser and internet, especially in mobile environments.

For example, the JuiceboxDAO logo is 11.2 MB and took 50seconds to load on a reasonable internet connection.

<img width="625" alt="Screen Shot 2022-01-07 at 9 27 43 pm" src="https://user-images.githubusercontent.com/94939382/148541410-356992cc-e399-4bab-97f8-be27daabcbd7.png">

## Proposal

Perhaps we should put a reasonable limit on image file sizes. My proposal would be 5 MB (this is arbitrary), but we could go more aggressive.

**Comment by peripheralist** [comment]
great suggestion. 5 MB seems like a good arbitrary limit
