### ISSUE TITLE
Add AMM price in Redeem modal

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#333]
## Proposal

Currently the AMM price is shown next to the pay button for projects with ERC20. We should also show this information in the Redeem modal, since a secondary market might represent an opportunity for users to get a better return in ETH.

**Comment by midnight-madman** [comment]
Hi @peripheralist, this sounds like a good first issue for me to tackle and start my journey into the codebase.

Two questions:
Is this still a relevant feature idea?
On which pages can I (in my dev environment) see the pay button for projects and the redeem modal?

Thank you! :)

**Comment by peripheralist** [comment]
hey @midnight-madman, this is still relevant and would be great to have!

The AMM components for Pay can be found in `AMMPrices/index.tsx`
Redeem modals are `RedeemModal.tsx` and `V2RedeemModal.tsx`

Also be sure to get a read of this doc if you haven't already. https://juicebox.notion.site/Become-a-paid-contributor-0d5a3f77fdb34da1bde73e5a824b2f2d. Just a heads up that for now, due to recently expanding our frontend team, we aren't currently onboarding new paid contributors

**Comment by midnight-madman** [comment]
@peripheralist thanks for the pointer to the components and for the heads up regarding joining the team.

I'd like to jump on anyway and give this a shot - will find some time in the next few days for this
