### ISSUE TITLE
[IDEA] Add ability to share Juicebox contribution to Twitter

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#339]
## Problem to solve

Raised in:
- https://discord.com/channels/775859454780244028/876252266594721873/929484817677053962
- https://twitter.com/altryne/status/1479925866985631747

> Juicebbox should prompt you to share immediately after contribution, with the link to the project and a hashtag of their choice TBH.

## Proposal

TBA, open to proposals. Probably use https://developer.twitter.com/en/docs/twitter-for-websites/web-intents/overview

## More details

_Add any other notes or screenshots about the feature request here._

**Comment by johnnyd-eth** [comment]
Decided against this one
