### ISSUE TITLE
[IDEA] Wrap `transactor()` hook instances into unique hooks

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#343]
## Problem to solve

transactor() hook instances lengthen files due to their complexity, and are occasionally reused.

## Proposal

Specific transactor() uses could be wrapped in their own hooks, which would:
- keep code organized
- prevent code duplication
- make it easier to add tests for creating transactions

## More details

![image](https://user-images.githubusercontent.com/79433522/148697206-97e7a468-91be-4fb8-9e62-539964fa5878.png)
Could become `usePay(note: string, preferUnstaked: boolean, value: BigNumber)` with other args derived from `ProjectContext`/`UserContext`

**Comment by aeolianeth** [comment]
Love this idea. I'm interested in getting more familiar with this code, so will assign myself if you're not already working on it.

**Comment by peripheralist** [comment]
done!
