### ISSUE TITLE
[IDEA] Add token's Sushiswap price to project page

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#344]
## Problem to solve

https://github.com/jbx-protocol/juice-interface/pull/311 added the Uniswap price of a project's token to the project page.

This issue is to add the Sushiswap price.

## Proposal

TBA

## More details

The design for multiple AMM's is still evolving, see https://www.notion.so/juicebox/Improvements-to-project-token-s-AMM-price-UI-26d285761c4848ccbc56ebed9b84eeb9

**Comment by peripheralist** [comment]
done!
