### ISSUE TITLE
[BUGish] Tooltips on DAO's very different to address tooltips

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#361]
## Description

The tooltips on DAO's have quite different styling to the tooltips on Addresses - looks kinda dodge IMO.

## Proposal

White text. On hover: blue and underline, and show another tooltip 'Go to Project'. Remove link icon. 

## Screenshots

<img width="534" alt="Screen Shot 2022-01-13 at 9 31 51 pm" src="https://user-images.githubusercontent.com/96150256/149322817-e37e57e1-c17e-4f04-981b-f734796ee3c6.png">

**Comment by carlbarrdahl** [comment]
Tooltips are generally not great for touch interfaces (the explicit ones with info icons are fine). 
One idea is to add an external link icon to the right of the DAO name and make sure the hit box is big enough for fingers to easily hit.
