### ISSUE TITLE
[BUG] Volume graph on individual project page

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#399]
## Summary

1. When reducing time range (e.g. 30days -> 7days), x axis goes crazy: stays at 30 day range and crams new graph into last 7 days. Then loads the correct graph a few seconds later. 

<img width="552" alt="Screen Shot 2022-01-19 at 11 47 21 am" src="https://user-images.githubusercontent.com/96150256/150048377-2d102809-d74f-44b1-a201-559bcdda7b6e.png">

...few seconds later...

<img width="555" alt="Screen Shot 2022-01-19 at 11 47 53 am" src="https://user-images.githubusercontent.com/96150256/150048413-ceb3737c-2550-4a79-bc77-91f39ada92da.png">

2. When increasing time range (7 -> 30days), expands x axis to 30 days before the full 30 days of the graph has loaded

<img width="535" alt="Screen Shot 2022-01-19 at 11 48 27 am" src="https://user-images.githubusercontent.com/96150256/150048437-c7280b1f-d193-4ec3-98e2-6b585d3e13df.png">

...few seconds later...

<img width="554" alt="Screen Shot 2022-01-19 at 11 48 42 am" src="https://user-images.githubusercontent.com/96150256/150048471-cc464c5e-2c6b-404e-a7de-e7ed94d832d3.png">

**Conclusion: **
Problem is with the `domain` attribute in the rechart `XAxis` component (BalanceTimeline:463). Component doesn't seem to have a responsive way of handling changes to this attribute, because the xTicks[0] is definitely updated when the graph re-renders. So It's a problem with rechart `XAxis`. I think if we redo the project page we should use a totally new graph module @aeolianeth

**Comment by aeolianeth** [comment]
@johnnyd-eth curious if this issue is solved with @wraeth-eth 's recent work in https://github.com/jbx-protocol/juice-interface/pull/1002. Feel free to close this issue if so!

**Comment by wraeth-eth** [comment]
Not perfect, but definitely mitigated:

https://user-images.githubusercontent.com/104132113/168701430-1dd4f1cc-41d6-4342-a4e1-d7af91d07594.mov

**Comment by aeolianeth** [comment]
Closing this for now.
