### ISSUE TITLE
Add 'distribute payouts' email notification

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#4200]

**Comment by wraeth-eth** [comment]
Very big feature - probably a separate prop

**Comment by tomquirk** [comment]
@wraeth-eth i think its actually not too bad.

1. Clone this file: src/pages/api/events/on-pay.ts
2. Change stuff to make it relevant to `distribute` event
3. Make new email template (clone the pay one, change it a bit)
4. Add `distribute` hook in etherhook

Def not more than a week
