### ISSUE TITLE
Expose Multisig info on projects that use a multisig

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#4222]
<img width="669" alt="Screenshot 2024-01-22 at 11 07 03 AM" src="https://github.com/jbx-protocol/juice-interface/assets/12551741/4fddd257-b3cb-4cae-af8d-2ee74fa61458">

**Comment by wraeth-eth** [comment]
Might need more info on this one @tomquirk

**Comment by tomquirk** [comment]
@wraeth-eth the idea is just to expose the multisig's signers and signing policy somewhere in the UI.

To answer the question: "who really owns this project and how much control do they have?"

Can use the Safe API for this:

<img width="683" alt="Screenshot 2024-03-16 at 1 22 40 PM" src="https://github.com/jbx-protocol/juice-interface/assets/12551741/f8cd07eb-20c1-4591-9550-fc9c1e771fd1">
