### ISSUE TITLE
[BUGish] Highlight project attributes that could indicate high risk for users

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#423]
## Description

Context:
- https://discord.com/channels/775859454780244028/789559668233601086/936083266233057311
- https://discord.com/channels/775859454780244028/879851197857677372/936459321716400140

Some project scenarios/configurations can be especially high risk for users, such as:
- **High supply of manually-minted tokens for an early project.** Current token holders will benefit from all payments to a project, and heavily dilute the share contributors.
- **Token minting is enabled (v1.1)** Any supply of tokens could be minted at any time by the project owners, diluting the token share of all existing contributors.
- **Ballot address is 0x0000...** Funding cycle reconfigurations can be created moments before a new cycle begins, giving project owners an opportunity to take advantage of contributors, for example by withdrawing overflow.
- **Reserved rate is 100% (or very high).** Contributors will receive a relatively small portion of tokens (if any) in exchange for paying the project.
- **Duration not set.** Reconfigurations can be made at any point without notice—similar to having a ballot address of 0x0000....
- **No funding target**: contributor can’t redeem 

> most of my concern comes from the
> - contributors so far
> - not using a multisig
> - questionably valid twitter followers
> 
> highlight parameters of projects that could indicate high risk to contributors (no fc duration, token minting allowed, high reserved rate, etc).

## Proposal

In any of these cases, the information should be highlighted on a project page, without a user needing to click into the funding cycle details.

![](https://cdn.discordapp.com/attachments/789559668233601086/936083265515847690/unknown.png)

**Comment by aeolianeth** [comment]
Closing for now, will continue to iterate and open a new issue if necessary.
