### ISSUE TITLE
Add ability to edit existing NFTs without overwriting

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#4260]
The latest contract functionality allows us to edit the existing NFT directly, rather than overwriting the existing collection (upsert vs replace). We should use the latest functionality.

<img width="405" alt="Screenshot 2024-02-20 at 6 38 02 PM" src="https://github.com/jbx-protocol/juice-interface/assets/12551741/a2031888-a460-4cab-9b23-817b9cdf6c20">

**Comment by wraeth-eth** [comment]
https://discord.com/channels/775859454780244028/942522503258054686/1218540684441813142
