### ISSUE TITLE
Add ability to see upcoming changes to payouts and reserved tokens

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#4261]
<img width="707" alt="Screenshot 2024-02-21 at 5 58 50 PM" src="https://github.com/jbx-protocol/juice-interface/assets/12551741/6696f119-be89-41d3-b3fa-0345f558679e">

**Comment by wraeth-eth** [comment]
This is a good feature - but also a huge PITA due to the way I built this. I might look at rewriting all this code to include this
