### ISSUE TITLE
Cant create a project on JBM

### ISSUE THREAD

**Issue by tomquirk** [jbx-protocol/juice-interface#4276]
flow breaks on "payouts" screen

https://discord.com/channels/775859454780244028/1216513999773106196

**Comment by wraeth-eth** [comment]
Looks like this was a cache issue, can we close this one?

**Comment by tomquirk** [comment]
@wraeth-eth eh 😓 the site full crashes in some state when navigating to payouts create page. Hard to reproduce of course, but I did have it happen to me the other day too.
