### ISSUE TITLE
[BUG] Paying project when not connected to wallet

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#443]
## Summary

With wallet disconnected, attempting to pay a project does not prompt user to connect their wallet. 

## What is the expected _correct_ behavior?

Should show wallet connect prompt. 

## Relevant logs and/or screenshots

https://user-images.githubusercontent.com/96150256/151700684-2a767e8f-16e0-463f-a9b2-1bfd48575fbf.mp4

**Comment by peripheralist** [comment]
thanks for logging this! i've noticed this bug on several other buttons that should initiate transactions (it might be all of them)
