### ISSUE TITLE
Does not work with IPFS companion.

### ISSUE THREAD

**Issue by MicahZoltu** [jbx-protocol/juice-interface#4473]
1. Install Firefox.
2. Install IPFS Companion browser extension.
3. Try to load https://juicebox.money/v2/p/618?tabid=nft_rewards
4. Notice that no NFTs show up.

The problem is that IPFS companion correctly redirects the remote IPFS requests to the user's configured IPFS gateway, such as a local node running via IPFS Desktop.  However, the CSP for juicebox.money blocks these requests and thus the page fails to load.

The purpose of using IPFS is to protect against censorship and allow people to self-host, and by having a CSP that disallows redirecting to local IPFS node it undermines the entire purpose of using IPFS.

**Comment by wraeth-eth** [comment]
Thank you for raising this issue and for your detailed explanation. We understand the value of IPFS in promoting decentralization and censorship resistance. However, our current CSP configuration is designed to prioritize security and mitigate vulnerabilities, which is a critical consideration for our platform.

At this time, we are not actively supporting third-party setups like local IPFS nodes. While we recognize the potential benefits, the risk-to-reward ratio does not align with our priorities. That said, if there is increased interest or compelling use cases in the future, we may revisit this decision.

We appreciate your feedback and encourage further discussion if there are alternative approaches that balance security and functionality.

Thank you for understanding!
