### ISSUE TITLE
[BUGish] Ask user to confirm when clicking out of Create/Reconfig menus with unsaved changes

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#469]
## Description

In the Create or Reconfiguration menus, it can be easy to accidentally click out of (and cancel) a form that you've already made changes in, causing the user to create a transaction with unintended properties.

## Proposal

If a user "Cancels" any form where fields have been changed from the initial value, we should should show a modal asking if they're sure they want to discard their changes. Architecturally, we may be able to do this by either comparing "current" values to "initial" values, or comparing values to the `EditingProject` state

**Comment by aeolianeth** [comment]
@johnnyd-eth I might remove this from FC 15 if our focus is going to be on V2. Let me know if you what you think.

**Comment by aeolianeth** [comment]
THanks @wraeth-eth !
