### ISSUE TITLE
Project list reflects mainnet in testnet

### ISSUE THREAD

**Issue by odd-amphora** [jbx-protocol/juice-interface#51]

**Comment by peripheralist** [comment]
Projects are currently queried using the Juicebox mainnet subgraph. We don't have a subgraph deployed to any testnets, but it shouldn't be too much work if it's necessary. An easier workaround might be to add a case in the Projects hook for when the user isn't connected to mainnet.

**Comment by odd-amphora** [comment]
What is the level of effort for this (adding testnet subgraph)? I think it should be included in v1 @mejango after WikiToken fiasco.

**Comment by odd-amphora** [comment]
Ah it is included! Great

**Comment by peripheralist** [comment]
@odd-amphora it'll require:
- A subgraph to be created, defined, and deployed for each testnet. Each subgraph definition should be the same as the subgraph for mainnet, just with different contract addresses
- A workflow that streamlines upgrading the testnet subgraphs alongside the mainnet subgraph
- A pattern for the UI to read from the correct subgraph based on the connected network
