### ISSUE TITLE
[BUGish] Remove `ethers` as project dependency

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#519]
## Description

`ethers` is responsible for a hefty `296KB` of the bundle size. I think we might be able to remove it and replace it with the `@ethersproject/<module>` sub-modules and save a bunch of bundle space.

<img width="236" alt="Screen Shot 2022-02-11 at 11 49 11 am" src="https://user-images.githubusercontent.com/94939382/153528475-fba8433e-863b-4801-874e-fcf780bf5da3.png">

## Proposal

Possible approach:
1. Run `yarn analyze` to get a baseline bundle size.
1. Grep the codebase for string `from 'ethers'`
1. Replace each import with the corresponding submodule import.

   ```diff
   - import { constants } from 'ethers'
   + import * as constants from '@ethersproject/constants'
   ```
1. Remove the `ethers` dependency (e.g. `yarn remove ethers`)
1. Run `yarn analyze` again and compare.

**Comment by aeolianeth** [comment]
> i didn't understood the grep part?

@RishiKumarRay one way to do that is "find all" in your code editor:

<img width="367" alt="Screen Shot 2022-02-12 at 8 38 32 am" src="https://user-images.githubusercontent.com/94939382/153682836-13e2e978-b839-4123-ab4a-6021c41fd1b2.png">

**Comment by RishiKumarRay** [comment]
@aeolianeth 
![Screenshot from 2022-02-12 10-32-30](https://user-images.githubusercontent.com/87641376/153697479-856e5405-8ec2-461b-a4fe-b6709e9f95b1.png)
getting these warnings for these sub modules

**Comment by aeolianeth** [comment]
> @aeolianeth ![Screenshot from 2022-02-12 10-32-30](https://user-images.githubusercontent.com/87641376/153697479-856e5405-8ec2-461b-a4fe-b6709e9f95b1.png) getting these warnings for these sub modules

@RishiKumarRay ah, looks like the `utils` is broken up across many modules. For example:

```diff
- import { utils } from 'ethers'
+ import { formatBytes32String } from '@ethersproject/strings'
// ...
- utils.formatBytes32String('')
+ formatBytes32String('')
```

This file might help you find which modules to import for various util functions: https://github.com/ethers-io/ethers.js/blob/master/packages/ethers/src.ts/utils.ts

**Comment by RishiKumarRay** [comment]
@aeolianeth one more thing in some places there are two functions together then what to implement like big number and constant are together then should i write their submodule together?

**Comment by aeolianeth** [comment]
> @aeolianeth one more thing in some places there are two functions together then what to implement like big number and constant are together then should i write their submodule together?

@RishiKumarRay  In that case, we can import them separately:

```diff
- import { BigNumber, constants } from 'ethers'
+ import * as constants from '@ethersproject/constants'
+ import { BigNumber } from '@ethersproject/bignumber'
```

**Comment by benschac** [comment]
Is anyone still working on this issue? I'd be happy to submit a PR.

**Comment by aeolianeth** [comment]
@benschac thanks for your interest! I gave this a crack in https://github.com/jbx-protocol/juice-interface/pull/639, and it looks good, although it doesn't appear to have a massive impact on chunk JS loaded (about 100kb, which is still quite good).

Going to investigate further 👍 . let me know if you have any thoughts.

**Comment by benschac** [comment]
Nice, I was looking at the PR and had a quick question. I'll comment there.
