### ISSUE TITLE
[IDEA] Add prettier/eslint rule to warn or error on `console` functions

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#528]
## Problem to solve

It's easy to accidentally leave `console.log()`s in the code during development.

## Proposal

We could add a rule to warn or error on these, which we could bypass in places we _do_ want to leave logs (like in the Transactor hook) by adding a `// @prettier-ignore ...` line

idea by @aeolianeth:
> For existing logs, we could create our own log function that is literally const log = console.log and use that everywhere we want to keep logs (like contract reads etc.) Then we only need to eslint-ignore for that one line/file

**Comment by aeolianeth** [comment]
Yes, please!!!! <3
