### ISSUE TITLE
[IDEA] Global cache for Trending Projects

### ISSUE THREAD

**Issue by peripheralist** [jbx-protocol/juice-interface#529]
## Problem to solve

Trending projects requires multiple graph queries to load all payments. This means
1) More GRT costs in paying for Graph queries
2) Increased loading time

## Proposal

1) Fetching Trending projects will save the information to a JSON file, and upload it to IPFS with a TTL value. 
2) Any user that loads the Trending projects page will initially fetch that file. 
3) If an expired TTL value is received, that user repeats step 1.

Note: changing the contents of the JSON cache will change the CID, meaning the file can't be accessed via a URI. We should be able to use this https://docs.pinata.cloud/pinata-node-sdk#pinlist to find the cache file, if it's saved using a unique metadata attribute.

Other challenges may be related to multiple users loading the expired TTL cache and attempting to upload a new version simultaneously.

**Comment by aeolianeth** [comment]
Done!
