### ISSUE TITLE
[IDEA] Add Archived state to project metadata 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#567]
## Problem to solve

<img width="827" alt="Screen Shot 2022-02-19 at 9 12 12 am" src="https://user-images.githubusercontent.com/96150256/154773241-f12e4773-733a-4fec-8c59-ca0dda1c1275.png">

## Proposal

- Add archived state to project metadata have a button for it in edit project details.
- Have a message sent to Discord informing us to manually add it to the Archived list 

Peri:
- To standardize archiving projects, what do y’all think of adding an “archived” property to project metadata? It’s been brought up in the past but we never talked much about it since we can’t filter projects by metadata. We’d still need to add them to a list manually, but having a property would at least allow projects to “verify” that they want to be archived. Maybe the form in the app also sends a message to discord to let us know, and we could include a message in the form saying “your project will be archived within a few days”

**Comment by aeolianeth** [comment]
Thanks @peripheralist for working on this! Closing 🚀
