### ISSUE TITLE
[BUGish] Add risk indicators to 'Review and deploy' modal

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#584]
Add all risk indicators to fields in 'Review and deploy' modal on project creation

**Comment by sticklo** [comment]
Hiii, 
I would love to take on this issue
could you please assign it to me and provide me with better insights as to what you expect my fix to be?

**Comment by johnnyd-eth** [comment]
Hey Sticklo! We have risk indicators appear on projects for particular settings which may appear risky to contributors (e.g. no funding cycle duration, reserved rate > 90%, token minting enabled, or no reconfiguration rules). I've attached a screenshot of all the ones I could remember off the top of my head (see the little (i) icons and hover for explanations). In the 'Review and deploy' modal, we aren't showing those indicators on those same fields when should be there. 

We'll want to look through the code the see if there are any risk indicators I've missed, check the conditions which cause them to be shown, and replicate it in the 'Review and deploy' modal. Thanks!

<img width="653" alt="Screen Shot 2022-03-23 at 10 55 41 pm" src="https://user-images.githubusercontent.com/96150256/159704739-b11ec344-14d5-436f-896c-62d004115232.png">

**Comment by aeolianeth** [comment]
Thanks @sticklo !
