### ISSUE TITLE
[BUGish] Show error message when payment fails

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#634]
## Description

When a user tries to pay a juicebox project and it fails, there is no feedback to the user. This leaves them confused.

## Proposal

Show a basic error message in the Payment modal

**Comment by johnnyd-eth** [comment]
I thought I did this at some point, but we should also prompt wallet connect if no wallet connected and user attempts a payment

**Comment by benschac** [comment]
Can I grab this issue?

**Comment by johnnyd-eth** [comment]
> Can I grab this issue?

Yeah would be huge @benschac go for it!

**Comment by benschac** [comment]
Quick questions:
> Show a basic error message in the Payment modal
I have been looking around for Modal Component Design (https://www.figma.com/file/8NjqzSpT8nO6MMlHbo8M5K/JBX-Component-Library?node-id=0%3A1) and Home page (https://www.figma.com/file/DczKN99Aaew2dL8Khtb4fE/JUICEBOX_HOMEPAGE?node-id=150%3A146) associated design for error messages.

Maybe I'm just looking in the wrong place. I haven't seen any design for an error message. 

Where could I find the error message design?

**Comment by aeolianeth** [comment]
> Where could I find the error message design?

@benschac there isn't one yet!

I would suggest we can use the antd `Notification` (with an error state) for this.

https://ant.design/components/notification/

We can use the `error` variant of the notification in this case.

Let me know if you have any trouble setting that up, and I'll try and point you in the right direction!

**Comment by zouantchaw** [comment]
is this still up for grabs?

**Comment by benschac** [comment]
I was going to work on it this weekend.

**Comment by benschac** [comment]
#738

**Comment by benschac** [comment]
I have a couple of questions:

1. https://github.com/jbx-protocol/juice-interface/blob/main/src/hooks/Transactor.ts#L194. There's already a notif for the failure of transactions. It seems like this code meets the requirement of the issue when triggered.

<img height="400" src="https://user-images.githubusercontent.com/2502947/160292706-879afb68-9a6d-443d-a515-fc3ced9f1b28.jpg" />



2. Is there a way most folks on the team force a transaction error/failure to test/confirm functionality? I manually tested this failure state by throwing an error in the try-catch block in the screenshot above. I'm curious if the culprit might be the transaction not throwing an error on failure?

**Comment by aeolianeth** [comment]
@benschac this is my bad, I should have been more specific in this issue description.

There's another "error" case that can occur _before_ the transaction is executed, here: https://github.com/jbx-protocol/juice-interface/blob/8056faf589c18d38c784210e3c2b43286c6c8421/src/hooks/v1/transactor/PayV1ProjectTx.ts#L20-L28

RIght now, if that condition is met, we silently do nothing, and the user doesn't know what happened. This happened recently where `terminal?.version` was undefined.

Looks like there's a few different ways to go about this, here's 2 ideas:
- we could add an `onError` callback to `Transactor.ts`, and call it when the precondition for the pay tx isn't met. Then, we set the `onError` callback of the pay tx to display the error notification.
- It looks like `usePayV1ProjectTx` returns a function that returns a promise: we could await that promise [here](https://github.com/jbx-protocol/juice-interface/blob/2d0d72a6b957b492cb8e5b0e920c6d74c8c17e95/src/components/v1/V1Project/modals/V1ConfirmPayOwnerModal/index.tsx#L58), and if the result is `false` display the error notification

But feel free to tackle however you think is best!
