### ISSUE TITLE
Project handle misaligned on "Edit Payouts" modal

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#701]
## Steps to reproduce

1. Go to a project page as a project owner. The project must have a payout to another juicebox project
2. Click "Edit payouts".
3. Observe.

## What is the _current_ bug behavior?

<img width="709" alt="Screen Shot 2022-03-19 at 12 57 15 pm" src="https://user-images.githubusercontent.com/94939382/159103352-5fb6116d-e82f-4e83-abbf-47a3fc1133b8.png">

## What is the expected _correct_ behavior?

<img width="694" alt="Screen Shot 2022-03-19 at 12 59 20 pm" src="https://user-images.githubusercontent.com/94939382/159103376-bca10665-6be4-41c3-b263-dd2103ed979f.png">

**Comment by sticklo** [comment]
can I grab this Issue ?

**Comment by aeolianeth** [comment]
@sticklo yes, of course!

**Comment by sticklo** [comment]
will do. thank you!
