### ISSUE TITLE
Update "available" funds number immediately after successful distribution

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#706]
## Description

When a user clicks "distribute funds" and it's successful, we don't automatically update the "AVAILABLE" number on the payouts card.

<img width="490" alt="Screen Shot 2022-03-21 at 11 01 07 am" src="https://user-images.githubusercontent.com/94939382/159192657-be904a8c-10e4-4b3c-a691-630c3fc66cb4.png">

## Proposal

Refresh this number immediately after the transaction is successful.

**Comment by wraeth-eth** [comment]
@aeolianeth please confirm if this is still a bug. From my testing:

https://user-images.githubusercontent.com/104132113/169684235-56be820b-42bc-4714-aa0f-85bb73dcc107.mov

**Comment by aeolianeth** [comment]
@wraeth-eth yeah we can close this. This was a bug before we refreshed the page after every transaction. Ideally we don't refresh the page, but such is life - closing!
