### ISSUE TITLE
Show input validation message when user's pay amount is 0

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#710]
## Description

The Pay button doesn't do anything when the payment amount is 0. This is a confusing UX.

## Proposal

We should include an input validation message when a user tries to pay 0 amount. Something like: `Pay amount must be greater than 0`.

## Screenshots

<img width="527" alt="Screen Shot 2022-03-21 at 1 44 54 pm" src="https://user-images.githubusercontent.com/94939382/159200830-fbccd41c-ddd3-44bd-8e25-8a00479641a7.png">

**Comment by WadeSellers** [comment]
I think I could give this 1 a shot. I think there's potential to add personality to this messaging while still indicating the button is connected to the number next to it. Kind of something like this mockup image only the dialog box would be of proper height.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/7055351/162299553-2a9d86e4-3fa7-40a8-a5eb-c23ee6d1e2d1.png">

**Comment by aeolianeth** [comment]
Done!
