### ISSUE TITLE
Improve link to Juicebox projects

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#745]
## Description

The tooltip on projects doesn't fit in with the style of address tooltips, and overall is unnecessary I think. 

<img width="532" alt="Screen Shot 2022-03-30 at 6 24 50 pm" src="https://user-images.githubusercontent.com/96150256/160887662-21da825f-15da-44aa-910a-99ac3f0925ad.png">

## Proposal

Remove the tooltip and link to projects straight from the handle

**Comment by aeolianeth** [comment]
@johnnyd-eth think this is a duplicate of https://github.com/jbx-protocol/juice-interface/issues/361, right?

**Comment by sticklo** [comment]
hey chief, can you please assign this issue to me? Thank you!
