### ISSUE TITLE
Make `ManageTokensModal` a single version-agnostic component

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#771]
## Description

_A clear and concise description of what could be better._

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by aeolianeth** [comment]
@johnnyd-eth thanks for creating this issue! I'll add it to the `juicebox.money` project, assign an iteration and add the milestone for better visibility 👍
