### ISSUE TITLE
[V2 project] Add. "Edit payouts" button and modal

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#785]
Mockup:

- next to heading
- add margin
- include the `cog` icon in the button

<img width="542" alt="Screen Shot 2022-04-18 at 8 14 53 pm" src="https://user-images.githubusercontent.com/94939382/163797657-0cd01f18-da4d-4a18-a0bb-f90e9b82e9f0.png">

**Comment by wraeth-eth** [comment]
![image](https://user-images.githubusercontent.com/104132113/168594496-321d7fc0-2a94-4bb4-a6a3-d142f04c7678.png)
Is this what you had in mind @aeolianeth ?

**Comment by wraeth-eth** [comment]
Is this what you had in mind @aeolianeth 
![image](https://user-images.githubusercontent.com/104132113/168595133-fcc46a55-bb74-4e3e-b961-a6b53003da3b.png)

**Comment by aeolianeth** [comment]
> Is this what you had in mind @aeolianeth ![image](https://user-images.githubusercontent.com/104132113/168595133-fcc46a55-bb74-4e3e-b961-a6b53003da3b.png)

yup!
