### ISSUE TITLE
Upcoming funding cycle card issues

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#809]
## Problem to solve

_Is your feature request related to a problem? Provide a clear and concise
description of what the problem is. Ex. I'm always frustrated when [...]_

## Proposal

_Describe the feature/solution you'd like. A clear and concise description of
what you want to happen._

## More details

_Add any other notes or screenshots about the feature request here._

**Comment by johnnyd-eth** [comment]
Problem is loading the queued shit in the `V2ProjectContext` and not having it update I believe

**Comment by aeolianeth** [comment]
> Problem is loading the queued shit in the `V2ProjectContext` and not having it update I believe

@johnnyd-eth would suggest we remove it from project context and load where needed (i.e. in the upcoming card)

**Comment by aeolianeth** [comment]
I think this is resolved. If its still sus after we fix ballots https://github.com/jbx-protocol/juice-interface/issues/826, we can re-open
