### ISSUE TITLE
Ballot strat not loading properly in reconfig modal

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#813]
## Problem to solve

Think this may also be a problem in V1 too actually. 

https://user-images.githubusercontent.com/96150256/163552800-54133779-a79f-47bf-988b-0bb752ae3b49.mp4

## Proposal

_Describe the feature/solution you'd like. A clear and concise description of
what you want to happen._

## More details

_Add any other notes or screenshots about the feature request here._

**Comment by aeolianeth** [comment]
@johnnyd-eth whats the actual ballot address on chain?

**Comment by johnnyd-eth** [comment]
> @johnnyd-eth whats the actual ballot address on chain, 0 or 3 day?

0 address I believe
