### ISSUE TITLE
Align project card with activity feed.

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#836]
## Summary

The activity feed is slightly vertically above the first project card on the homepage:

<img width="1145" alt="Screen Shot 2022-04-21 at 10 40 38 am" src="https://user-images.githubusercontent.com/94939382/164352013-919f1283-f36f-48e2-bf95-2cf6ac9d344b.png">

We should vertically align these.

**Comment by wraeth-eth** [comment]
https://github.com/jbx-protocol/juice-interface/pull/854
