### ISSUE TITLE
Make languages in footer a single row

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#837]
## Problem to solve

We currently have links to each language vertically stacked in the footer.

<img width="1088" alt="Screen Shot 2022-04-21 at 10 44 23 am" src="https://user-images.githubusercontent.com/94939382/164352303-63cb6651-dee6-42d8-a2e4-3748944acc89.png">

## Proposal

For a small footer/better UX, we should instead list these horizontally across the page. Links should wrap around to a new row.

**Comment by wraeth-eth** [comment]
https://github.com/jbx-protocol/juice-interface/pull/843
