### ISSUE TITLE
Make the timestamp on activity items clickable

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#838]
## Problem to solve

In the activity feed, we show the time of the activity, and small button that links to the transaction on Etherscan.

<img width="525" alt="Screen Shot 2022-04-21 at 10 47 13 am" src="https://user-images.githubusercontent.com/94939382/164352526-ec9fb958-f4f3-4828-8546-1993437b6915.png">

## Proposal

Remove the link icon button, and make the timestamp the link to the transaction on Etherscan.

The timestamp should have the same styling as currently, but underline on hover. Links should be opened in a new window (potentially use `ExternalLink` component: `src/components/shared/ExternalLink.tsx`)

**Comment by ritsuyan** [comment]
@aeolianeth how to assign this issue to me ? I am new here

**Comment by ritsuyan** [comment]
something confused me.
I am on the main branch.
1. the link icon already removed.
2.  on the '0x....' wallet address text already link to the Etherscan after click.
3.  the '19 hours ago' text has a timestamp tooltip when hover the itself. so should just click the text link to the Etherscan meanwhile remove the tooltip ?
@aeolianeth

**Comment by aeolianeth** [comment]
@ritsuyan the proposal is to "Remove the link icon button, and make the timestamp the link to the transaction on Etherscan."

| current | proposal |
| --- | --- |
| <img width="146" alt="Screen Shot 2022-04-28 at 8 52 23 pm" src="https://user-images.githubusercontent.com/94939382/165741696-b24058e7-bd70-4186-9f28-594899640bb3.png"> | <img width="150" alt="Screen Shot 2022-04-28 at 8 52 08 pm" src="https://user-images.githubusercontent.com/94939382/165741734-eb5f9b0e-c94a-4786-b5f9-3815bb88807e.png"> |

Clicking "9 hours ago" should link to the transaction in Etherscan.

Let me know if you need further clarification! 🙏

**Comment by ritsuyan** [comment]
> @ritsuyan the proposal is to "Remove the link icon button, and make the timestamp the link to the transaction on Etherscan."
> 
> current	proposal (hover state)
> <img alt="Screen Shot 2022-04-28 at 8 52 23 pm" width="146" src="https://user-images.githubusercontent.com/94939382/165741696-b24058e7-bd70-4186-9f28-594899640bb3.png">	<img alt="Screen Shot 2022-04-28 at 8 52 08 pm" width="150" src="https://user-images.githubusercontent.com/94939382/165741734-eb5f9b0e-c94a-4786-b5f9-3815bb88807e.png">
> Clicking "9 hours ago" should link to the transaction in Etherscan. The "9 hours ago" should be underlined on-hover.
> 
> Let me know if you need further clarification! 🙏

but under the timestamp already has a wallet address that can link to to the transaction in Etherscan when hover it.

**Comment by aeolianeth** [comment]
@ritsuyan 

**the current functionality**

- the wallet address below the timestamp links to the wallet address.
- the link icon links to the transaction.

**what we want**:
- remove the link icon.
- make the timestamp ("9 hours ago") link to the transaction. It should be underlined on-hover to indicate that it is a link.
- keep the wallet address as-is

**Comment by deeayeen** [comment]
https://user-images.githubusercontent.com/35680780/167772265-b7bee7f1-773b-4b1e-8ce4-df83fa35d2cb.mov

Solved in https://github.com/jbx-protocol/juice-interface/pull/980
