### ISSUE TITLE
FAQ image clipping out of parent element

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#844]
## Summary

when opening the:

Do I have to make my project open source to use Juicebox as its business model?

the format is off and causes it to break out and extend the page on mobile.

## Steps to reproduce

1. Expand the FAQ Item on mobile
2. See error with image

## What is the _current_ bug behavior?

 Unintended expansion out of page expected bounds.

## What is the expected _correct_ behavior?

presumably correctly sized image within element bounds

## Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/104132113/164889375-a4e0cbc8-f747-4b57-8e00-f8d02478f82a.png)

## Environment

Safari iPhone 13 Pro

**Comment by aeolianeth** [comment]
@wraeth-eth thanks for creating this 🙏 . Got a screenshot of the bug for reference?

**Comment by wraeth-eth** [comment]
Updated @aeolianeth
