### ISSUE TITLE
V2 QA Testing plan

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#846]
We need to QA all V2 transactions.

Im lieu of a testing framework, we need to do this manually.

## How to test

1. Perform the scenario (for example, change an input field, move a slider, etc.)
2. Click the **review and deploy** tab.
3. Click **deploy project to rinkeby** button at the bottom of the screen.
4. Open the browser console.
5. Locate the transaction request log to view the payload that will be sent on-chain.
    It will read: `calling <transaction> with args:`
   
    <img width="719" alt="Screen Shot 2022-04-22 at 3 07 47 pm" src="https://user-images.githubusercontent.com/94939382/164610416-1870b6f8-d289-4e31-ae59-189b65013f17.png">

6. Validate that the **expected value** is present in the transaction request payload.
7. Update the **works?** column with ✅  if it works, ❌ if it doesn,t and add your name to the **tested by** or **confirmed by** column.

⚠️ **NOTE**: some values are in hexadecimal. To convert to decimal, either:
- use this site: https://www.rapidtables.com/convert/number/hex-to-decimal.html
- use the console (this might break sometimes due to overflow): 
   ```js
   parseInt('0x0de0b6b3a7640000', 16);
   ```

### `launchProjectFor`

**Get started**

Start at the V2 Create form: https://rinkeby.juicebox.money/#/v2/create

| scenario | data field | expected value | works? | tested by | confirmed by |
| --- | --- | --- | --- | --- | --- |
| duration is disabled | `_data.duration` | 0 |  ✅   | @aeolianeth | @wraeth-eth  |
| duration is 1 day | `_data.duration` | 86400 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| duration is 1 second | `_data.duration` | 1 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| duration is 14 days | `_data.duration` | 1209600 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| distribution limit is `Zero` | `_fundAccessContraints[0].distributionLimit` | 0 |  ✅  | @JayZeeDesign | @wraeth-eth  |
| distribution limit is `No limit` | `_fundAccessContraints[0].distributionLimit` | MaxUint248 | ✅ it says '0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff' i assume right?  | @JayZeeDesign  | @wraeth-eth |
| distribution limit is 1 ETH | `_fundAccessContraints[0].distributionLimit` | 1,000,000,000,000,000,000 (10e18) | ✅  | @JayZeeDesign  | @aeolianeth  |
| distribution limit is 69 ETH | `_fundAccessContraints[0].distributionLimit` | 69,000,000,000,000,000,000 | ✅  | @JayZeeDesign  | @wraeth-eth |
| distribution limit is 0.5 ETH | `_fundAccessContraints[0].distributionLimit` | 500,000,000,000,000,000 |✅   | @JayZeeDesign  | @wraeth-eth |
| distribution limit is 1 USD | `_fundAccessContraints[0].distributionLimit` | 1,000,000,000,000,000,000 (10e18) | ✅  | @JayZeeDesign  | @wraeth-eth |
| distribution limit is in ETH | `_fundAccessContraints[0].distributionLimitCurrency` | 1 | ✅  | @JayZeeDesign  | @wraeth-eth |
| distribution limit is in USD | `_fundAccessContraints[0].distributionLimitCurrency` | 2 | ✅  | @JayZeeDesign  | @wraeth-eth |
| reserved rate is disabled | `_metadata.reservedRate` | 0 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| reserved rate is 100% | `_metadata.reservedRate` | 10,000 |  ✅  | @JayZeeDesign  | @wraeth-eth  |
| reserved rate is 69% | `_metadata.reservedRate` | 6,900 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| reserved rate is 1.5% | `_metadata.reservedRate` | 150 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| discount rate is disabled | `_data.discountRate` | 0 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| discount rate is 20% | `_data.discountRate` | 200,000,000 |  ✅   |  @wraeth-eth | tba |
| discount rate is 1.5% | `_data.discountRate` | 15,000,000 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| redemption rate is disabled | `_metadata.redemptionRate` | 10,000 |  ✅  | @JayZeeDesign  | @wraeth-eth |
| redemption rate is 100% | `_metadata.redemptionRate` | 10,000 |  ✅   | @JayZeeDesign  | @wraeth-eth |
| redemption rate is 69% | `_metadata.redemptionRate` | 6,900 |  ✅  | @JayZeeDesign  | @aeolianeth  |
| redemption rate is 1.5% | `_metadata.redemptionRate` | 150 |  ✅   | @JayZeeDesign  | @wraeth-eth |
| "pause payments" is disabled | `_metadata.pausePay` | false |  ✅  | @JayZeeDesign  | @wraeth-eth |
| "allow token minting" is disabled | `_metadata.allowMinting ` | false |  ✅  | @JayZeeDesign  | @wraeth-eth |
| "pause payments" is enabled | `_metadata.pausePay` | true |  ✅  | @JayZeeDesign  | @wraeth-eth |
| "allow token minting" is enabled | `_metadata.allowMinting ` | true |  ✅  | @JayZeeDesign  | @wraeth-eth |
| payout split of 10.25% | `_groupedSplits[0].splits[0].percent` | 102,500,000 | ✅ | @aeolianeth | @wraeth-eth |
| payout split of 100% | `_groupedSplits[0].splits[0].percent` | 1,000,000,000 | ✅ | @aeolianeth | @wraeth-eth |
| reserved split of 10.25% | `_groupedSplits[1].splits[0].percent` | 102,500,000 | ✅ | @aeolianeth | tba |
| reserved split of 100% | `_groupedSplits[1].splits[0].percent` | 1,000,000,000 | ✅ | @aeolianeth | tba |

### `pay`

| scenario | data field | expected value | works? | tested by | confirmed by |
| --- | --- | --- | --- | --- | --- |
| pay 1 ETH |

**Comment by wraeth-eth** [comment]
Confirmed testing:
| scenario | data field | expected value | received value | passed |
| --- | --- | --- | --- | --- |
| duration is disabled | `_data.duration` | 0 |  0x00 (0) | ✅  |
| duration is 1 day | `_data.duration` | 86400 | 0x015180 86400 | ✅  |
| duration is 1 second | `_data.duration` | 1 |   0x01 (1) | ✅  |
| duration is 14 days | `_data.duration` | 1209600 |   0x127500 (1209600) | ✅  |
| distribution limit is `Zero` | `_fundAccessContraints[0].distributionLimit` | 0 |  0x00 (0) | ✅  |
| distribution limit is `No limit` | `_fundAccessContraints[0].distributionLimit` | MaxUint248 |  0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff (4.523128485832664e+74) | ✅  |
| distribution limit is 1 ETH | `_fundAccessContraints[0].distributionLimit` | 1,000,000,000,000,000,000 (10e18) |  0x0de0b6b3a7640000 (1e18) | ✅  |
| distribution limit is 69 ETH | `_fundAccessContraints[0].distributionLimit` | 69,000,000,000,000,000,000 |  0x03bd913e6c1df40000 (6.9e+19) | ✅  |
| distribution limit is 0.5 ETH | `_fundAccessContraints[0].distributionLimit` | 500,000,000,000,000,000 |  0x06f05b59d3b20000 (5e+17) | ✅  |
| distribution limit is 1 USD | `_fundAccessContraints[0].distributionLimit` | 1,000,000,000,000,000,000 (10e18) |  0x0de0b6b3a7640000 (1e+18) | ✅  |
| distribution limit is in ETH | `_fundAccessContraints[0].distributionLimitCurrency` | 1 |  0x01 (1) | ✅  |
| distribution limit is in USD | `_fundAccessContraints[0].distributionLimitCurrency` | 2 |  0x02 (2) | ✅  |
| reserved rate is disabled | `_metadata.reservedRate` | 0 |   0x00 (0) | ✅ |
| reserved rate is 100% | `_metadata.reservedRate` | 10,000 |   0x2710 (10,000) | ✅  |
| reserved rate is 69% | `_metadata.reservedRate` | 6,900 |   0x1af4 (6,900) | ✅  |
| reserved rate is 1.5% | `_metadata.reservedRate` | 150 |   0x96 (15) | ✅   |
| discount rate is disabled | `_data.discountRate` | 0 |   0x00 (0) |✅ |
| discount rate is 20% | `_data.discountRate` | 200,000,000 |  0x0bebc200 (200,000,000) |✅  |
| discount rate is 1.5% | `_data.discountRate` | 15,000,000 |   0xe4e1c0 (15,000,000) |✅  |
| redemption rate is disabled | `_metadata.redemptionRate` | 10,000 |  0x2710 (10,000) |✅  |
| redemption rate is 100% | `_metadata.redemptionRate` | 10,000 |   0x2710 (10,000) |✅  |
| redemption rate is 69% | `_metadata.redemptionRate` | 69,000 |   0x1af4 (6,900) | ❌  |
| redemption rate is 1.5% | `_metadata.redemptionRate` | 150 |   0x96 (150) |✅  |
| "pause payments" is disabled | `_metadata.pausePay` | false |   false |✅  |
| "allow token minting" is disabled | `_metadata.allowMinting ` | false |   false |✅  |
| "pause payments" is enabled | `_metadata.pausePay` | true |   true |✅  |
| "allow token minting" is enabled | `_metadata.allowMinting ` | true |  true |✅  |
| payout split of 10.25% | `_groupedSplits[0].splits[0].percent` | 102,500,000 |  102,500,000 | ✅  |
| payout split of 100% | `_groupedSplits[0].splits[0].percent` | 1,000,000,000 |  1,000,000,000 | ✅  |
| reserved split of 10.25% | `_groupedSplits[1].splits[0].percent` | 102,500,000 |  TBD | 🟠  |
| reserved split of 100% | `_groupedSplits[1].splits[0].percent` | 1,000,000,000 |  TBD | 🟠  |


@aeolianeth Re `distribution limit is 1 ETH` - did you mean 1e18?

Not sure how to do reserved splits via the UI - might need some help

**Comment by aeolianeth** [comment]
@wraeth-eth fucking legend man thank you so much.

The redemption rate one was a typo, the value you got was correct 👍
