### ISSUE TITLE
`DistributedRatio` still sometimes not rendering properly

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#850]
## Summary

<img width="583" alt="Screen Shot 2022-04-22 at 5 32 46 pm" src="https://user-images.githubusercontent.com/96150256/164756785-825edcd4-3b91-43fa-b974-9fdf67c0035d.png">

This is `v2/p/12` on Rinkeby. Think it's because the `currencyOption` that's coming through is 0 when it has to be 1 or 2 for v2

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by aeolianeth** [comment]
@johnnyd-eth nice pick up.

Quick note on good first issues (which we haven't defined anywhere, just my take): good first issues should be ones that:
- literally anyone with no knowledge of this codebase at all can come in and fix within an hour
- are very tightly scoped with clear instructions/guidelines on the intended outcome

A good example is this https://github.com/jbx-protocol/juice-interface/issues/837

**Comment by wraeth-eth** [comment]
Hey @johnnyd-eth, i've been digging into this one and am having trouble to get this to happen to a newly minted project.
I have created two projects:
## ETH as the currency
- http://localhost:3000/#/v2/p/46
![image](https://user-images.githubusercontent.com/104132113/166097682-a8981e3c-8764-4694-ae9b-b5d959c373ef.png)

## USD as the currency
- http://localhost:3000/#/v2/p/46
![image](https://user-images.githubusercontent.com/104132113/166097693-e2946bd9-91d6-4413-b5ed-a392a283f283.png)

FWIW - I looked at the values for p12 and this is what they are:
```
distributionLimit: BigNumber {_hex: '0x0de0b6b3a7640000', _isBigNumber: true}
distributionLimitCurrency: BigNumber {_hex: '0x00', _isBigNumber: true}
usedDistributionLimit: BigNumber {_hex: '0x00', _isBigNumber: true}
```

so it seems like you are right about the `distributionLimitCurrency` being `0`, however I am not quite sure why this is the case here.
