### ISSUE TITLE
Page shows white area when overscrolling

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#853]
## Summary

When scrolling on either mobile or browser, overscrolling at the bottom will show white after the header.

## Steps to reproduce

1. Scroll down to footer and then 'overscroll'.
2. White is shown.

## What is the _current_ bug behavior?
White shown on overscroll

## What is the expected _correct_ behavior?
We should consider being consistent with the footer color for 'immersion'.

## Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/104132113/164874616-771f10e7-1d70-41b3-b243-1cb09781f952.png)

## Environment
Any device or machine

**Comment by jmilldotdev** [comment]
How do we feel about fixing this using:

```css
body: {
   overscroll-behavior-y: none;
}
```

This is the simplest solution but can have some unintended consequences. We don't use pull-to-refresh anywhere do we?

**Comment by sticklo** [comment]
@jmilldotdev  I don't think we use pull-to-refresh anywhere on the page
