### ISSUE TITLE
Edit Payouts modal: Payout amount input is not pre-set 

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#874]
## Summary

TBA

<img width="532" alt="Screen Shot 2022-04-27 at 11 26 24 am" src="https://user-images.githubusercontent.com/94939382/165422812-dd6c4854-ca41-443d-848f-0e797ac4f07d.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by wraeth-eth** [comment]
@aeolianeth is there anything specific that needs to be done to recreate this?
![image](https://user-images.githubusercontent.com/104132113/166098226-1c26f615-f9cb-4e61-a85b-9dc0d1a83f3f.png)
THis is form a newly minted project

**Comment by wraeth-eth** [comment]
Ah just found out this occurs on the create - rather than existing project
