### ISSUE TITLE
Add page for projects the connected wallet is owner of. 

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#875]
## Description

_A clear and concise description of what could be better._

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by wraeth-eth** [comment]
I like this idea! Really useful and coordinated UX for a user to quickly find all of their projects in one place

**Comment by jmilldotdev** [comment]
Could this simply be an additional tab in the projects page?

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/33093632/166456956-c256646a-fc94-454f-ac4e-8020199c1084.png">
