### ISSUE TITLE
Spelling error in Issue Tickets

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#884]
## Summary

Issue tickets is missing a word - "Would you to issue", should be "Woudl you **like** to issue"

## Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/104132113/165955087-11088fbb-ca78-4c6b-bf59-8b293e435b63.png)

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by hyungjunk** [comment]
How do I make a PR with no push permission? I've read the contribution guide and couldn't find a right way to do it.
