### ISSUE TITLE
Minor style bug in V1 tools modal

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#891]
## Summary

![stylebug](https://user-images.githubusercontent.com/96150256/166114888-3ee5a589-b23f-4d56-8bd5-eed0f9be0f34.png)

May also exist in V2 please check

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by jmilldotdev** [comment]
Duplicate of #899, closed by #909. This component is shared between v1 and v2.
