### ISSUE TITLE
Create a way to load already deployed `ProjectPayer` addresses of a project 

### ISSUE THREAD

**Issue by johnnyd-eth** [jbx-protocol/juice-interface#897]
## Description

https://discord.com/channels/775859454780244028/786985806396784690/970392917577437214

Would be great to show payable address of a project in the tools modal in this section:

https://user-images.githubusercontent.com/96150256/166159931-e4f93dde-221c-47f5-bcf7-5ce7983821a9.mp4

Or even just on the project page

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by aeolianeth** [comment]
@johnnyd-eth we could store the preferred payable address in metadata 🤔
