### ISSUE TITLE
Label overflowing on "add to balance" input

### ISSUE THREAD

**Issue by aeolianeth** [jbx-protocol/juice-interface#899]
## Summary

`Payout amount` label is overflowing

It also should say "Pay amount" instead.

<img width="572" alt="Screen Shot 2022-05-02 at 5 48 47 am" src="https://user-images.githubusercontent.com/94939382/166163108-84e85b29-9c60-4c87-85c5-0371b6396f76.png">

## Steps to reproduce

On a project you own (or in dev):

1. Go to `Tools` drawer by clicking the wrench in the top-right.
2. Observe.

**Comment by jmilldotdev** [comment]
I can fix the label, but imo to really fix this we should bump antd to 4.18.0+ since it adds a `labelWrap1` property to the form API to handle overflow on translations.
