### ISSUE TITLE
v2 pay modal use of ENS as beneficiary doesn't work

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#920]
## Summary

Use of ENS as beneficiary doesn't validate properly

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/33093632/166467963-d5f302e7-9aaa-44a2-835e-51865f804df6.png">

## Steps to reproduce

Type ENS
Attempt to pay

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by aeolianeth** [comment]
Think this is solved now. Pls reopen if not
