### ISSUE TITLE
V2 Add Reconfiguration Review Screen that shows all changes that will be made on redeploy

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#933]
## Problem to solve

This is just a screen that could be shown after where users currently click repdeploy configuration so that they can review their changes

## Proposal

_Describe the feature/solution you'd like. A clear and concise description of
what you want to happen._

## More details

_Add any other notes or screenshots about the feature request here._

**Comment by aeolianeth** [comment]
@wraeth-eth is this dupe of https://github.com/jbx-protocol/juice-interface/issues/825

**Comment by wraeth-eth** [comment]
Yeah it is will close
