### ISSUE TITLE
V2 Project: Reconfigure Button missing when first deployed project

### ISSUE THREAD

**Issue by wraeth-eth** [jbx-protocol/juice-interface#951]
## Summary

Appears after refreshing

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by jmilldotdev** [comment]
I can't reproduce this

**Comment by wraeth-eth** [comment]
Might have been a blip, I can't recreate now either. Thanks for looking into @jmilldotdev
