### ISSUE TITLE
No projects load by default when clicking on the 'All' tab in /projects

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#993]
## Summary

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/33093632/168094282-813443d2-c947-4dc7-a978-7e070beed7cb.png">

## Environment

- **Device/OS**: [e.g. iOS]
- **Browser:** [e.g. chrome, safari]
- **Hardware wallet**: [e.g. Ledger w/ Metamask]

**Comment by wraeth-eth** [comment]
Hey @jmilldotdev - do you have some steps to repeat for this one? Currently, when I click all on https://juicebox.money/#/projects I see:

https://user-images.githubusercontent.com/104132113/168271933-65ec0392-d654-493a-9e1f-c542f9375c3c.mov

**Comment by jmilldotdev** [comment]
yeah i think it's a problem with the subgraph URL i'm using.
