### ISSUE TITLE
Don't hide tabs and filter/sort controls when a user is searching projects

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#995]
## Description

From a UX standpoint, it feels a bit weird that we hide the controls and require a user to clear their search to get the tabs/filters back. This is also related to a small quirk where if a user clears their search string, they cannot clear their search with the x button to get the controls back.

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/33093632/168095437-5aa6558b-c7de-445e-9380-f1d7991667dd.png">

## Proposal

Leave tabs and filter/sort available even if a user has an active search.

## Screenshots

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/33093632/168095668-23590eac-29a1-4249-8df1-88a41b0e822e.png">

(Can't clear my search due to empty string, can't get tabs/filters back until i clear it or do an empty search)

**Comment by johnnyd-eth** [comment]
@peripheralist I believe we've hidden this because currently the filter and sort won't work when there's a search string present? How hard will it be to get them to be friendly with each other do you think?

**Comment by peripheralist** [comment]
That's right. When we search we're actually querying a different entity than Projects, check the useProjectsSearch hook. The graph doesn't support querying with a `where` argument in addition to the `text` argument we use with search, meaning we can't search and filter at the same time

**Comment by wraeth-eth** [comment]
@tomquirk how would you feel about downgrading this one from bug to just a feature request?

**Comment by tomquirk** [comment]
ya totally
