### ISSUE TITLE
Browser 'back' button has to be clicked twice to go back to /projects from a project page

### ISSUE THREAD

**Issue by jmilldotdev** [jbx-protocol/juice-interface#996]
## Description

Title. Click any project from the projects page, wait for it to load. You will have to click 'back' twice to get pack to /projects.

## Proposal

_A description of the change you'd like to see._

## Screenshots

_If applicable, add screenshots to help explain your problem._

**Comment by wraeth-eth** [comment]
Hey @jmilldotdev trying to recreate this one. Do you think we could get more info on steps to repeat? Having trouble recreate this one.

**Comment by jmilldotdev** [comment]
hmmm yeah seems like it's only happening on brave for me, and doesn't happen in incognito mode. must be some extension conflict.
